### ISSUE TITLE
Внедрение электронного документооборота

### ISSUE THREAD

**Issue by SvetlanaSV** [diadoc/diadoc1cpro-docs#1]
Мы внедряем ВЭД в нашу систему. В связи с этим появился вопрос. Прошу вас проконсультировать.
Мы используем типовую обработку для загрузки документов. В подключаемом модуле я вижу, что если приходит одна счет-фактура от контрагента (она имеет тип документа «invoice»), то такой документ один не загружается в систему. Выдает сообщение «Документ на создан в подключаемом модуле». В самой обработке стоит фильтр, если счет-фактура приходит одна, без пакета, то с таким типом документа она не загружается. Нам необходимо понимать в связи с чем стоит такая настройка? И как нам правильно загружать такие документы?
Еще подскажите пожалуйста как я могу получить подпись к нужному документу? Мы хотим хранить в нашей системе все документы, которые приходят от Диадока и подписи к ним. Сами документы я вижу, они копируются в указанную папку на диск, а вот файла подписи я не вижу. Нам нужно доказательство того, что файл был подписан контрагентом.

**Comment by nvyhodceva** [comment]
Здравствуйте!

Напишите, пожалуйста, версию модуля, которую внедряете.
Для релиза 2.3.0 логика следующая:

1. В самом распространенном сценарии работы пользователей предполагается создание Счета-фактуры только вместе с накладной. Если есть документ с функцией InvoiceAndBasic или Basic, то сначала создается документ "Поступление товаров и услуг", а затем счет-фактура на его основании. Логика создания документа заложена в функции подключаемого модуля ПолучитьЗаполненныйОбъектДокумента1С. Вы можете реализовать удобный для Вас способ создания документов.

2. Подпись к нужному документу содержится в файле ТитулПокупателя.sgn.  Загрузка происходит при установленном признаке "Загружать документооборот целиком" в настройках на закладке "Хранилище документов".
