### ISSUE TITLE
Реквизит "Запросить подпись контрагента"

### ISSUE THREAD

**Issue by milanse** [diadoc/diadoc1cpro-docs#102]
В форме пакета для неформализованного документа хотелось бы видеть реквизиты **Запросить подпись контрагента** и **Комментарий**, чтобы можно было поменять их перед отправкой. Сейчас их видно если создаешь такой документ руками, но не видно если документ создается автоматом в ПМ.

**Comment by ButurlakinSemyon** [comment]
@milanse добрый день!
Уточните пожалуйста информацию:
1. Версию вашего модуля
2. Пример ПМ или более подробное описание (какой документ создаете)
3. Запрос подписи и комментарий нужен в карточке документа на отправку?

**Comment by milanse** [comment]
Форма пакета:

![image](https://user-images.githubusercontent.com/15941393/186912192-da963a1d-2b5d-40f0-9dd1-9a24213c3052.png)

ПФ счет на оплату в пакет добавляю так:

`
		ИмяВремФайла = ПолучитьИмяВременногоФайла("pdf");
		
		ОбъектыПечати = Новый СписокЗначений;
		
		МассивОбъектов = Новый Массив;
		МассивОбъектов.Добавить(Документ1С);
		ТабДокумент = Документы.ПУ_СчетНаОплату.ПечатьСчетНаОплату(МассивОбъектов, ОбъектыПечати, "ПФ_MXL_СчетНаОплату");	
		
		ТабДокумент.Записать(ИмяВремФайла, ТипФайлаТабличногоДокумента.PDF);
		
		Результат.Метаданные.DocumentDate	= Документ1С.Дата;
		Результат.Метаданные.DocumentNumber	= СокрЛП(Документ1С.Номер);
		Результат.Метаданные.FileName		= "Счет на оплату " + СокрЛП(ДанныеДокумента.Номер) + ".pdf";
		
		Результат.ДвоичныеДанные			= Новый ДвоичныеДанные(ИмяВремФайла);
		УдалитьФайлы(ИмяВремФайла);
		Результат.ИмяФайла					= "Счет на оплату " + СокрЛП(ДанныеДокумента.Номер) + ".pdf";	
		Результат.Content.Date				= ДанныеДокумента.Дата;
		Результат.Content.Number			= ДанныеДокумента.Номер;	
		Результат.Сумма 					= Документ1С.Товары.Итог("СуммаСНДС");
`

**Comment by milanse** [comment]
@ButurlakinSemyon ?

**Comment by NikitaLysenkoA** [comment]
@milanse в служебную информацию необходимо добавить структуру ПараметрыОтправки, в ней ключ ЗапрашиватьОтветнуюПодпись 
`Результат.СлужебнаяИнформация.ПараметрыОтправки.ЗапрашиватьОтветнуюПодпись = Истина;`

**Comment by milanse** [comment]
@NikitaLysenkoA ,шаманство, какое-то.

Вставил так:
![image](https://user-images.githubusercontent.com/15941393/212852172-7513fe02-4700-4e0a-8aca-41810bc8fb20.png)

Реквизиты на форме отправки не появились:

![image](https://user-images.githubusercontent.com/15941393/212852397-5a35fdb7-b7e7-41f3-aaee-ef25f18774dd.png)

**Comment by NikitaLysenkoA** [comment]
Сама галочка на форме не появится)

**Comment by milanse** [comment]
> Сама галочка на форме не появится)

В этом и состоит запрос )

**Comment by milanse** [comment]
@DmitryModin , а чего задачу то закрыли ? Я все еще не могу регулировать требование обратной подписи в документах добавленных программно.
