### ISSUE TITLE
Не отображается код товара (ItemVendorCode) в печатной форме УПД

### ISSUE THREAD

**Issue by MarinaKononchuk** [diadoc/diadoc1cpro-docs#104]
Добрый день.

Версия модуля: 4.17.4.1922
Версия плагина: 1.4.3.195
Расположение модуля: ВКонфигурации
Конфигурация: 1С:ERP Управление предприятием 2 (2.5.7.394)
Модуль интеграции: ПМ_УТ_11

Необходимо, чтобы для определенных позиций номенклатуры в УПД выводился код товара/работ (колонка "А" в таб.части УПД).
Заполняем в контенте исходящего документа (в таб.части Content.Table.Items) поле ItemVendorCode. В печатной форме данного документа колонка не заполняется, хотя в xml файле (по кнопке "Сохранить документ" на форме пакета) поле КодТов заполнено.

В обработке ПечатныеФормы.epf при заполнении строки табличного документа (например, процедура ПФ_УПД_820_СтрокиТаблицы()) параметр "Код" заполняется только если пустое наименование и характеристика:

Область.Параметры.Код = ПредставлениеКодТов_736_820(Item, Параметры.ВыводитьНаименованиеТовараСКодами);

Это можно как-то обойти через подключаемый модуль?

**Comment by IrinaShmonina** [comment]
@MarinaKononchuk , добрый день,
обратитесь в нашу техническую помощь любым удобным способом - https://www.diadoc.ru/support 
Вам помогут настроить визуализацию
