### ISSUE TITLE
Отправка УПД в конкретное подразделение получателя

### ISSUE THREAD

**Issue by WildSery** [diadoc/diadoc1cpro-docs#111]
В самом УПД нет никакого указания на маршрутизацию.
Куда и в какой объект необходимо вносить данные о подразделении получателя документа?

**Comment by DmitryModin** [comment]
Добрый день!
Указать подразделение, в которое вы хотите отправить документ, можно открыв сам пакет и под наименованием контрагента будет еще одна строка для выбора его подразделения.
![image](https://user-images.githubusercontent.com/96285259/189332517-a48ae146-eb6c-41aa-8774-f032777114f4.png)

**Comment by WildSery** [comment]
Этот способ я знаю.
Но Диадок.ПРО устанавливают не для того, чтобы руками заполнять маршрутизацию.
В каком объекте и событии программно (в подключаемом модуле, желательно) можно указать подразделение получателя?

**Comment by WildSery** [comment]
Похоже, у разработчиков более важные дела, всё приходится делать самому.
Решение для тех, кому потребуется самостоятельно решать проблему маршрутизации.

Событие "ПодготовитьПакет" подключаемого модуля.

Для отправки в конкретное подразделение получателя следует в пакете заполнить ID и Ссылку.
В моём случае, найти нужное подразделение-получатель я могу только по КПП, потому я выполняю такой код:

```
	КПП = ""; // тут я получил КПП не типовым образом

	Запрос = Новый Запрос(
	"ВЫБРАТЬ ПЕРВЫЕ 1
	|	Подразделения.Ссылка,
	|	Подразделения.ID
	|ИЗ
	|	Справочник.Диадок_ЮрФизЛица КАК Подразделения
	|ГДЕ
	|	Подразделения.ИмяСправочника = ""ПодразделенияКонтрагентов""
	|	И Подразделения.КПП = &КПП
	|	И Подразделения.ID_ВладелецПодразделения = &Владелец
	|
	|УПОРЯДОЧИТЬ ПО
	|	Подразделения.КПП,
	|	Подразделения.ID_РодительПодразделения");
	Запрос.УстановитьПараметр("Владелец", Параметры.Пакет.Получатель.BoxId);
	Запрос.УстановитьПараметр("КПП", КПП);

	Выборка = Запрос.Выполнить().Выбрать();
	Если Выборка.Следующий() Тогда
		// нашли подразделение, заполняем данные маршрутизации
		Параметры.Пакет.Получатель.Подразделение = Выборка.Ссылка;
		Параметры.Пакет.Получатель.DepartmentId = Выборка.ID;
	КонецЕсли;
```

**Comment by acharushkin** [comment]
@WildSery 

> В самом УПД нет никакого указания на маршрутизацию. Куда и в какой объект необходимо вносить данные о подразделении получателя документа?

Можно сопоставить объекты 1С с подразделениями в сервисе. С помощью методов `ОсновнойМодуль.ЭДО_Справочники_ИдентификаторПодразделенияКонтрагента` и `ОсновнойМодуль.ЭДО_Справочники_ИдентификаторПодразделенияОрганизации` можно получать идентификаторы диадочных подразделений, сопоставленных с нужными тебе объектами.

```bsl
Функция ПослеПодготовкиПакета(Параметры)
   
   Пакет = Параметры.Пакет;

   ИдентификаторОтправителя = Пакет.ДанныеДД.BoxId;
   ИдентификаторПолучателя = Пакет.ДанныеДД.CounteragentBoxId;

   Пакет.ДанныеДД.FromDepartmentId = ОсновнойМодуль.ЭДО_Справочники_ИдентификаторПодразделенияОрганизации(СвязанныйОбъектОтправителя, ИдентификаторОтправителя);
   Пакет.ДанныеДД.ToDepartmentId = ОсновнойМодуль.ЭДО_Справочники_ИдентификаторПодразделенияКонтрагента(СвязанныйОбъектПолучателя, ИдентификаторПолучателя);
   
КонецФункции
```

В этом примере `СвязанныйОбъектОтправителя` - ссылка на любой объект, сопоставленный с подразделениями отправителя в настройках организации (подразделение, договор, склад и т.д.), а `СвязанныйОбъектПолучателя` - ссылка на любой объект, сопоставленный с подразделениями получателя в карточке получателя (контрагент, партнёр, договор и т.д.)
