### ISSUE TITLE
Подключаемый модуль Стандарт в модуле "Универсальный"

### ISSUE THREAD

**Issue by PNK1C** [diadoc/diadoc1cpro-docs#112]
Здравствуйте! В модуле 4.18.0 поддержано выполнение события ОбработатьСобытиеПослеЗаполненияКонтента подключаемого модуля Стандарта. Для этого нужно:
- В модуле Стандарт (Диадок 5.55) подключить подключаемый модуль.
- Запустить модуль "Универсальный" (Контур.Диадок / 4.18.0.1960)
- При формировании документов контент будет заполнен с учетом логики события ОбработатьСобытиеПослеЗаполненияКонтента 

Но лучше перенести доработки события в подключаемый модуль "Универсальный" (Контур.Диадок / 4.18.0.1960). С методами можно ознакомиться в [документации](https://developer.kontur.ru/Docs/Diadoc_UM/proc/pm/Podgotovka_Paketa_Dlya_Otpravki.html). Или воспользоваться инструментом ["Генератор ПМ"](https://developer.kontur.ru/Docs/Diadoc_UM/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D0%B2/Generator_PM.html).

_Originally posted by @kulakovskaya in https://github.com/diadoc/diadoc1cpro-docs/issues/106#issuecomment-1228387690_

Добрый день, я открыл модуль "Универсальный" в базе где уже был старый модуль с подключенным модулем. Код отработал, как и в старой версии, однако почему-то при переходе в меню модуля "Универсальный" отобразилось, что "Подключаемого модуля" нет, хотя он есть.

Хотим переделать на новые методы, но возник вопрос:

У нас будет две конфигурации (сейчас используется УПП и постепенно переходим на ЕРП), для шаблона подключаемого модуля получается используется:
Для УПП 1.3 лучше всего использовать «ПМ_УТ_103_epf»
А для ЕРП 2.5 лучше всего использовать «ПМ_УТ_11_epf»?

Проверил по инструкции "Генератор ПМ", там как я понял, тоже самое, то есть для УПП - УТ 10.3, а для ЕРП УТ 11?

Еще вопрос касательно новой структуре, не нашел описание, где хранится табличная часть документа, раньше в структуре Контента была табличная часть.

Также вопрос как отключить использование старого "подключаемого модуля"? Просто перейти на вкладку "Подключаемый модуль" и выбрать новый - он перезатрет прошлое значение и можно ли будет потом обратно вернуть старый модуль (если не сразу сработает корректно новый)?

**Comment by ButurlakinSemyon** [comment]
@PNK1C Добрый день!

> Добрый день, я открыл модуль "Универсальный" в базе где уже был старый модуль с подключенным модулем. Код отработал, как и в старой версии, однако почему-то при переходе в меню модуля "Универсальный" отобразилось, что "Подключаемого модуля" нет, хотя он есть.

Вкладка "Подключаемый модуль" (ПМ) в настройках Универсального модуля предназначена для файлов ПМ, которые были написаны именно для Универсального модуля. ПМ от стандарта действительно не будет отображаться на данной вкладке, но его наличие можно посмотреть в окне технической информации:
![image](https://user-images.githubusercontent.com/74642650/190072248-ee7ff868-690a-4d7d-921a-e0394d1b0c0f.png)

> для шаблона подключаемого модуля получается используется: 
> Для УПП 1.3 лучше всего использовать «ПМ_УТ_103_epf»
> А для ЕРП 2.5 лучше всего использовать «ПМ_УТ_11_epf»?

Для корректной подготовки шаблона ПМ следует использовать плагин "[Генератор ПМ](https://developer.kontur.ru/Docs/Diadoc_UM/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D0%B2/Generator_PM.html)" или команду "Генерировать шаблон" в настройках модуля на вкладке "Подключаемый модуль". В том и другом случаях у вас сгенерируется шаблон кода, который вы сможете перенести в файл ПМ. 
Использовать ПМ_УТ_103_epf или ПМ_УТ_11_epf в качестве подключаемого модуля не рекомендуется, так как это может привести к невозможности получения обновлений.

> Еще вопрос касательно новой структуре, не нашел описание, где хранится табличная часть документа, раньше в структуре Контента была табличная часть.

Если речь идет про табличную часть входящего электронного документа, то пример получения ниже:
```
ФайлXML = ОсновнойМодуль.ЭДО_ПолучитьХранилищеКонтента(ИдентификаторЭД);
Контент = ОсновнойМодуль.XML_В_ProtoСтруктура(ФайлXML);
```
В переменной "Контент" получим содержание электронного документа, включая все табличные части.

> Также вопрос как отключить использование старого "подключаемого модуля"? Просто перейти на вкладку "Подключаемый модуль" и выбрать новый - он перезатрет прошлое значение и можно ли будет потом обратно вернуть старый модуль (если не сразу сработает корректно новый)?

Нет, вкладка "Подключаемый модуль" предназначена только для работы с файлом ПМ для Универсального модуля, то есть ПМ от старого модуля в таком случае не затрется.
Отключить старый ПМ можно двумя способами:
1. Открыть старый модуль и отключить использование ПМ в настройках.
2. Перейти в регистр сведений "Дополнительные сведения" (для конфигураций на управляемых формах) или в регистр сведений "Значения свойств объектов" (для конфигураций на обычных формах) и установить значение "Нет" для записи со свойством "ИспользоватьПодключаемыйМодуль":

![image](https://user-images.githubusercontent.com/74642650/190078145-009329bc-68d5-4f85-8c45-dccc3eb58a9d.png)

**Comment by PNK1C** [comment]
Спасибо большое за разъяснения.
