### ISSUE TITLE
Ошибка в событии ПолучитьТекстЗапросаДляСпискаПакетовНаОтправкуПоМассивуВидовПакетов подключаемого модуля

### ISSUE THREAD

**Issue by Kernel001** [diadoc/diadoc1cpro-docs#114]
Техническая информация:

Версия модуля: 4.19.3.1965
Версия плагина: 1.4.4.220
Модуль типовой: Да
Система хранения: Типовые объекты 1С
Расположение модуля: ВСправочнике
Имя модуля: 
Конфигурация: "Управление торговлей", редакция 10.3 (10.3.49.1)
Модуль интеграции: ПМ_УТ_103

Подключаемый модуль на диске: \\srv-fs-1\Box\Группа ОИ\Обработки\Диадок_ПМ.epf
Тип платформы: Windows x86-64
Версия платформы: 8.3.18.1433
Версия ОС: version 10.0  (Build 18362)
Вид клиента: Толстый клиент обычное приложение
Строка соединения: Srvr="192.168.0.28";Ref="UT";
Каталог временных файлов: C:\Users\kopilov-as\AppData\Local\Temp\

В подключаемом модуле задействована обработка события ПолучитьТекстЗапросаДляСпискаПакетовНаОтправкуПоМассивуВидовПакетов. Изменен слегка запрос для фильтрации контрагентов и отображения головного контрагента вместо конечного. При этом в случайном порядке появляется ошибки при обновлении списка документов:

Выполнение операции: HTTP запрос в сервис diadoc-api2.kontur.ru.
Ошибка HTTP запроса
Код ошибки: 400
boxid: could not get boxid from query param
Метод: GET
Адрес метода: https:// diadoc-api2.kontur.ru/GetBox

Выполнение операции: Обновление списка документов.
{ВнешняяОбработка.КонтурВнешниеСервисы.МодульОбъекта(173)}: Ошибка HTTP запроса
Код ошибки: 400
boxid: could not get boxid from query param
		ВызватьИсключение ТекстОшибки;

Зависит от дней отображения, в некоторых днях этой ошибки нет. Судя по всему это связано с какимито документами и отсутствием свойств в этих документа, но каких непонятно. ПМ генерировался с помошью плагина.

**Comment by DmitryModin** [comment]
Добрый день!
Приложите. пожалуйста, сам ПМ, который используете.
Спасибо!

**Comment by Kernel001** [comment]
[Диадок_ПМ.zip](https://github.com/diadoc/diadoc1cpro-docs/files/9571509/_.zip)

**Comment by NikitaLysenkoA** [comment]
@Kernel001 если отключить ПМ, то ошибка уходит?

**Comment by NikitaLysenkoA** [comment]
Или можно переопределить параметры без переопределения самого запроса (возможно он устарел)
Пример тут:
[ПМ_DDS-51615.zip](https://github.com/diadoc/diadoc1cpro-docs/files/9572571/_DDS-51615.zip)

**Comment by Kernel001** [comment]
> 

Да, если отключить ПМ, то ошибки нет

**Comment by Kernel001** [comment]
Там не только параметры меняются, но и поля некоторые, без переопределения запроса результат ПМа будет не полный :(

**Comment by NikitaLysenkoA** [comment]
Какие именно поля? Можно показать в коде?

**Comment by NikitaLysenkoA** [comment]
А головной контрагент сопоставлен в модуле? И дружит ли он с вашей организацией?
Если это не так, то BoxId пустой и как раз будет возникать такая ошибка как у вас.

**Comment by NikitaLysenkoA** [comment]
Потому что BoxId вычисляется по карточке контрагента 1С, и если у вас подмена контрагента, то BoxId может отсутствовать.

**Comment by NikitaLysenkoA** [comment]
Еще я бы связь поменял.
![image](https://user-images.githubusercontent.com/102023443/190394596-839b08fc-5362-413c-8357-141273454575.png)

Для каких целей заменяется контрагент?

**Comment by Kernel001** [comment]
Ммм... да, похоже на то! Спасибо. Связь выделенная из типового кода. А контрагент меняется для удобства работы бухгалтеров (их заказ). Это обясняет почему ошибка стала появляться реже. Почти всех контрагентов уже сопоставили (включая головных). Спасибо за помощь!
