### ISSUE TITLE
Изменить представление договора в УПД в ПМ

### ISSUE THREAD

**Issue by dionidy** [diadoc/diadoc1cpro-docs#117]
День добрый,

подскажите, какое поле отвечает за представление Договора?
сейчас туда принудительно записывается "Договор № и дата договора"

![Сохраненное изображение 2022-9-16_13-59-19 829](https://user-images.githubusercontent.com/29654595/190613871-a0c0bb43-6b4d-4e77-b32b-66866404efc7.jpg)

![Сохраненное изображение 2022-9-16_13-58-23 864](https://user-images.githubusercontent.com/29654595/190613875-65b1c570-3f12-499a-bd86-4556ebea6d21.jpg)

**Comment by dionidy** [comment]
Разобрался, вдруг кому поможет:

НужныеРеквизиты = Новый Структура;
НужныеРеквизиты.Вставить("ДоговорКонтрагента");
ЗначенияРеквизитов = ОбщегоНазначения.ЗначенияРеквизитовОбъекта(Результат.Документ1С, НужныеРеквизиты);
Content.TransferInfo.TransferBases[0].DocumentName = ЗначенияРеквизитов.ДоговорКонтрагента.Наименование;

**Comment by DmitryModin** [comment]
Добрый день!
Рады, что вам удалось разобраться. Если будут вопросы, обращайтесь.
