### ISSUE TITLE
Как обратиться к списку документов из подключаемого модуля

### ISSUE THREAD

**Issue by Andrey1702002434** [diadoc/diadoc1cpro-docs#123]
Добрый день! Подскажите пожалуйста, каким образом получать списки документов с различными фильтрами в подключаемом модуле? Я использовал метод, который нашел в одном из ваших подключаемых модулей: ОсновнойМодуль.ЭДО_Модуль_ОбновитьСписокДокументов(ПараметрыОбновленияСписка);
СписокДок = ОсновнойМодуль.СписокДокументов;

Но, проблема в том, что при построении http запроса используются параметры из общего контекста, а именно АдресКонтекстаСеанса. При получении списка документов в модуле объекта обработки Диадок контекст сеанса заполнен.
При обращении из подключаемого модуле он не заполнен. Без него, насколько я понял, список документов получить не возможно

**Comment by WildSery** [comment]
КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();

**Comment by AndreyM17** [comment]
Спасибо за информацию! Но, не получилось. Наверное нужно было подробнее описать, мое упущение. 
Я вызываю процедуру "ВыполнитьРегламентныеДействия" из подключаемого модуля. Причем вызов происходит с помощью регламентного задания, созданного в 1С. Т.е. внешняя обработка Диадок в момент запуска регламента не открыта, а передается как параметр регламентного задания 1С. (делал примерно так, как описано здесь - https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html) 
Проблема в том, что я не могу в данному случае обратиться к списку документов ЭДО и контексту сеанса из процедуры "ВыполнитьРегламентныеДействия" подключаемого модуля. Получаю пустые значения, вместо заполненных таблицы значений и соответствия. Может это вообще невозможно?

**Comment by WildSery** [comment]
Всё правильно, именно в процедуре "ВыполнитьРегламентныеДействия" подключаемого модуля это и делается.
Выгрузите шаблон подключаемого модуля, там закомментированный пример.

Как-то вот так:
```
Функция ВыполнитьРегламентныеДействия(Параметры) Экспорт

	// 1. Авторизация под сертификатами сервера 1С
	ОсновнойМодуль.ЭДО_АвторизоватьсяПодСертификатомНаСервере1С();  
	КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();
	
	// 2. Параметры для получения списка пакетов на отправку
	ТаблицаВидовПакетов	 = ОсновнойМодуль.ЭДО_СправочникМенеджер_ПолучитьСписокЭлементов("ВидыПакетов");
	МассивВидовПакетов	 = ТаблицаВидовПакетов.ВыгрузитьКолонку("Ссылка");
	
	ПараметрыОбновленияСписка = Новый Структура;
	ПараметрыОбновленияСписка.Вставить("Режим",					"ОтправкаПакетов");
	ПараметрыОбновленияСписка.Вставить("НачалоПериода",			ДобавитьМесяц(ТекущаяДата(), -2));
	ПараметрыОбновленияСписка.Вставить("КонецПериода",			КонецДня(ТекущаяДата()));
	ПараметрыОбновленияСписка.Вставить("МассивВыбранныхВидов",	МассивВидовПакетов);
	
	//3. Отправка пакетов по организациям, в которых авторизовались под сертом сервера 1С
	Для Каждого Элемент Из КонтекстСеанса Цикл
		
		СтрокаКонтекста	 = Элемент.Значение;
		Организация		 = СтрокаКонтекста.ОрганизацияДиадок.СвязанныйСправочник1;
		
		ПараметрыОбновленияСписка.Вставить("ОтборПоОрганизации", Организация);
		
		ОсновнойМодуль.ЭДО_Модуль_ОбновитьСписокДокументов(ПараметрыОбновленияСписка);
		
		//1 вариант: последовательная отправка
		Для Каждого СтрокаТЧ Из ОсновнойМодуль.СписокДокументов Цикл
		КонецЦикла;
		
		////2 вариант: фоновая отправка
		//ОсновнойМодуль.ЭДО_ПодготовитьИОтправитьПакетыВФоне(ОсновнойМодуль.СписокДокументов);
		
	КонецЦикла;	
	
	Возврат Истина;
КонецФункции
```

**Comment by AndreyM17** [comment]
Дело в том, что в переменной КонтекстСеанса (КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();) получается соответствие без данных, пусто. Может при вызове из общего модуля конфигурации (регламентное задание) нужно передавать какие-то параметры? У меня так происходит вызов процедуры "ВыполнитьРегламентныеДействия":

Процедура РегламентныеДействияДиадок(Параметры) Экспорт
	
       //Сообщить("Это вызов модуля из конфигурации 1С");
	
	ВнешняяОбработкаДиадок = Параметры.ОбработкаДиадок;
	ИмяФайла = ПолучитьИмяВременногоФайла("epf");
	ДвоичныеДанные = ВнешняяОбработкаДиадок.ХранилищеВнешнейОбработки.Получить();
	ДвоичныеДанные.Записать(ИмяФайла);
	ВнешняяОбработкаДиадок = ВнешниеОбработки.Создать(ИмяФайла);
	
	
ВнешняяОбработкаДиадок.ВыполнитьКоманду("ЭДО_ВыполнитьРегламентныеДействия");
	

КонецПроцедуры

**Comment by WildSery** [comment]
*тру хрустальный шар*

Возможно, в процедуре "ВыполнитьРегламентныеДействия" подключаемого модуля у вас нет вызова авторизации.
Под сертификатом или логином-паролем.

Например
ОсновнойМодуль.ЭДО_АвторизоватьсяПодСертификатомНаСервере1С();

**Comment by AndreyM17** [comment]
Есть. Вот текст модуля(вставил фрагмент, который вы ранее присылали):

ОсновнойМодуль.ЭДО_АвторизоватьсяПодСертификатомНаСервере1С();  
	КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();
	
	// 2. Параметры для получения списка пакетов на отправку
	ТаблицаВидовПакетов	 = ОсновнойМодуль.ЭДО_СправочникМенеджер_ПолучитьСписокЭлементов("ВидыПакетов");
	МассивВидовПакетов	 = ТаблицаВидовПакетов.ВыгрузитьКолонку("Ссылка");
	
	ПараметрыОбновленияСписка = Новый Структура;
	ПараметрыОбновленияСписка.Вставить("Режим",					"ОтправкаПакетов");
	ПараметрыОбновленияСписка.Вставить("НачалоПериода",			ДобавитьМесяц(ТекущаяДата(), -2));
	ПараметрыОбновленияСписка.Вставить("КонецПериода",			КонецДня(ТекущаяДата()));
	ПараметрыОбновленияСписка.Вставить("МассивВыбранныхВидов",	МассивВидовПакетов);
	
	//3. Отправка пакетов по организациям, в которых авторизовались под сертом сервера 1С
	Для Каждого Элемент Из КонтекстСеанса Цикл
		
		СтрокаКонтекста	 = Элемент.Значение;
		Организация		 = СтрокаКонтекста.ОрганизацияДиадок.СвязанныйСправочник1;
		
		ПараметрыОбновленияСписка.Вставить("ОтборПоОрганизации", Организация);
		
		ОсновнойМодуль.ЭДО_Модуль_ОбновитьСписокДокументов(ПараметрыОбновленияСписка);
		
		//1 вариант: последовательная отправка
		Для Каждого СтрокаТЧ Из ОсновнойМодуль.СписокДокументов Цикл
		КонецЦикла;
		
		////2 вариант: фоновая отправка
		//ОсновнойМодуль.ЭДО_ПодготовитьИОтправитьПакетыВФоне(ОсновнойМодуль.СписокДокументов);
		
	КонецЦикла;

**Comment by WildSery** [comment]
А у вас вообще отправка УПД регламентным работает, или вы только настраиваете?
Зайдите в отладку и посмотрите, может. у вас авторизация не проходит.

**Comment by AndreyM17** [comment]
Не совсем так. Регламентное задание нужно не для отправки УПД. Задача в том, чтобы собрать пул подписанных документов и отправить их в Директум. Пока сделано следующим образом: При закрытии формы обработки Диадок вызывается процедура, которая записывает данные в служебный регистр сведений. Затем регламентным заданием по расписанию данные из служебного регистра выгружаются в Директум. Мне хотелось сделать запись данных в служебный регистр также с помощью регламентного задания, когда внешняя обработка Диадок не запущена. Но, видимо, это невозможно. Пробовал по разному, по итогу таблица документов всегда пустая получается

**Comment by AndreyM17** [comment]
Возможно я что-то не так делаю. Вот код, который расположен в модуле внешней обработки Диадок и он работает:

ПараметрыОбновленияСписка = Новый Структура;
	ПараметрыОбновленияСписка.Вставить("Режим",					"ПолученныеДокументы");
	ПараметрыОбновленияСписка.Вставить("НачалоПериода",			НачалоМесяца(ТекущаяДата()));
	ПараметрыОбновленияСписка.Вставить("КонецПериода",			НачалоМесяца(ДобавитьМесяц(ТекущаяДата(),+1)));
	ПараметрыОбновленияСписка.Вставить("ОтборПоСтатусу",	    Модуль_Ядро().Перечисление_СтатусыДокументов().Подписан);
	
	ТаблицаДанныхДиадок = ТаблицаДанныхДиадок();
	
	ДокументыДляСписка = Модуль_Ядро().СписокДокументов_Документы(ПараметрыОбновленияСписка);
	КонтекстСеанса = ПолучитьИзВременногоХранилища(ОбщийКонтекстКлиентСервер.АдресКонтекстаСеанса);
	Для Каждого Элемент Из КонтекстСеанса Цикл
		СтрокаКонтекста	 = Элемент.Значение; 
		BoxId = СтрокаКонтекста.BoxId;
	КонецЦикла;

**Comment by AndreyM17** [comment]
Но, если я этот код размещаю в подключаемом модуле (процедура "ВыполнитьРегламентныеДействия) - возвращает пустую таблицу документов. Пробовал по разному ( в том числе фрагмент, который вы ранее скидывали с авторизацией), под отладкой тоже смотрел конечно. Да, и еще КонтекстСеанса - также возвращает пустой

**Comment by WildSery** [comment]
Если контекст сеанса пустой, то авторизация не выполнена, скорее всего.
У вас сертификат на сервере установлен?
Попробуйте авторизацию логин/пароль, только проверьте в Диадоке, что у этого логина права на все документы есть.

**Comment by Detashe** [comment]
Столкнулся с похожей проблемой пустого контекста. После авторизации по логину/паролю контекст нужно заполнить дополнительно, а после авторизации под сертификатом контекст должен заполниться автоматически.
ОсновнойМодуль.ЭДО_ЗаполнитьКонтекстСеансаДляСлужебнойУчетнойЗаписи();
