### ISSUE TITLE
Акт сверки взаиморасчетов - исправить запрос

### ISSUE THREAD

**Issue by PNK1C** [diadoc/diadoc1cpro-docs#124]
Добрый день, коллеги.

Не смог самостоятельно найти, как решить следующую задачу при переходе на "Универсальный модуль".

Необходимо внести исправления в запрос формирования акта сверки, а также в представление документа. 

В прошлой версии модуля, делал это через внесение исправлений в модуле "Модуль_ИнтеграцияУПП13" в функции "ПолучитьДанныеТЧАктаСверки": 

В запрос необходимо было добавить "ДокументРегистратор"
	                |	АктСверкиВзаиморасчетовПоДаннымКонтрагента.ДокументРегистратор,

Чтобы потом в зависимости от документа формировать представление: 

//Стр.представлениеДокумента = выборка.Представление; 
 Стр.представлениеДокумента = ПолучитьПредставлениеДокумента(ПолучитьСчетФактуру(выборка.ДокументРегистратор));

В Универсальном пока не смог найти аналогичную функцию при формировании акта сверки.

Подскажите, пожалуйста, как можно внести исправления в запросе акта сверки и "представлениеДокумента"?

Конфигурация: Управление производственным предприятием, редакция 1.3 (1.3.183.1) 
Версия модуля: 4.20.0.1998

**Comment by IrinaShmonina** [comment]
Добрый день,
чтобы внести изменения в акт сверки зайдите в макеты → выгрузите типовой модуль диадок → из него модуль интеграция УПП 1.3 → дальше нужно найти функцию ПолучитьДанныеТЧАктаСверки()
![image](https://user-images.githubusercontent.com/19413034/197141137-a7a1d410-c9e5-4885-a93c-896d4415e556.png)

**Comment by PNK1C** [comment]
Спасибо, помогло.
