### ISSUE TITLE
Перед отправкой документа изменить подразделение контрагента получателя

### ISSUE THREAD

**Issue by FroZenOne1** [diadoc/diadoc1cpro-docs#129]
Привет. Есть часть сетевых контрагентов которые подключены к Диадок  и имеют несколько подразделений.
Ни как не получается прописать их автоматическую установку например в зависимости от выбранной в документе Торговой точки.
Надо ли это делать  тут- "ПослеПодготовкиПакета"

В документации примера работы с подразделениями нет

**Comment by DmitryModin** [comment]
Добрый день!
Вы можете сопоставить несколько организаций\подразделений из 1С с одним контрагентом в Диадоке.
При формировании документа вы указываете нужное подразделение контрагента и документ буден направлен именно ему. 
Или сценарий отличается от описанного мной?

**Comment by FroZenOne1** [comment]
Сценарий такой  - В реализации есть ДоработанныйРеквизит - ТороговаяТочка. 
С именем Например "Ленина 20 - кафэ".  контрагент равно  "ИП Иванов"
Соответственно связки Контрагент  + Подразделение = КОнтранет1с + ИмяТорговой точки нет. 
У контрагента есть Подразделение названное "Магазин ленина 20". К примеру мы заносим такое наименование в доп свойство к нашему реквизиту "Торговая точка". 
И перед отправкой хотелось бы его найти идентифицировать и подставить в доумент.

**Comment by WildSery** [comment]
Авторы при невозможности прямого сопоставления предлагают только ручную отправку.

Читайте здесь одно из решений для автоматизации https://github.com/diadoc/diadoc1cpro-docs/issues/111
Вам главное найти нужное подразделение в Справочник.Диадок_ЮрФизЛица и подставить в реквизиты пакета.

**Comment by acharushkin** [comment]
> Сценарий такой - В реализации есть ДоработанныйРеквизит - ТороговаяТочка. С именем Например "Ленина 20 - кафэ". контрагент равно "ИП Иванов" Соответственно связки Контрагент + Подразделение = КОнтранет1с + ИмяТорговой точки нет. У контрагента есть Подразделение названное "Магазин ленина 20". К примеру мы заносим такое наименование в доп свойство к нашему реквизиту "Торговая точка". И перед отправкой хотелось бы его найти идентифицировать и подставить в доумент.

Привет!

Маршрутизацию по подразделениям контрагента можно реализовать программно с помощью события `ПослеПодготовкиПакета`. Примеры кода [тут](https://github.com/diadoc/diadoc1cpro-docs/issues/111#issuecomment-1322039772)
