### ISSUE TITLE
Проблемы при настройки регламентного задания.

### ISSUE THREAD

**Issue by VitalyaSamohvalov** [diadoc/diadoc1cpro-docs#13]
1С:Предприятие 8.3 (8.3.6.2152) - "Управление торговлей", редакция 10.3 (10.3.11.4) 

Написал обработку для теста регламентного задания, в будущем планируем загружать документы и выгружать.
Если запустить с клиента, то работает, а через фоновое выполнение выдает ошибки.
![изображение](https://user-images.githubusercontent.com/75297793/100830686-2d563180-349f-11eb-8f53-70d1785898ec.png)

Код фоновой обработки.
```
Процедура ВыполнитьОбработку() Экспорт
		
	СсылкаОбработки_ДиадокПро = Справочники.ВнешниеОбработки.НайтиПоКоду("Б00000747");
	ДвоичныеДанные = СсылкаОбработки_ДиадокПро.ХранилищеВнешнейОбработки.Получить();
	ИмяФайла = ПолучитьИмяВременногоФайла("epf");
	ДвоичныеДанные.Записать(ИмяФайла);
	Объект_ДиадокПро = ВнешниеОбработки.Создать(ИмяФайла);	
	
	Кэш = Новый Соответствие;
	Кэш.Вставить("ЭтоОбычноеПриложение", Истина);
	
	ПараметрыПМ = Новый Структура("ЗапускСКлиента", Ложь);
	Объект_ДиадокПро.Кэш = Кэш;
	Объект_ДиадокПро.ВыполнитьКоманду("ЭДО_ВыполнитьРегламентныеДействия",ПараметрыПМ);	
	
КонецПроцедуры
```
В [данной](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html) инструкции не наблюдаю описание вызова регламентного задания из вне.
Как правильно прописать вызов функций из вашей обработки?

**Comment by volodkindv** [comment]
Вам надо отключить безопасный режим для обработки. Попробуйте так, например:
```
Процедура ВыполнитьОбработку() Экспорт
	...
	Объект_ДиадокПро = ВнешниеОбработки.Создать(ИмяФайла, Ложь);
	...
	
КонецПроцедуры
```

**Comment by VitalyaSamohvalov** [comment]
После смены темы вопроса, я нашел решение в других вопросах.

Решение примерно выглядит теперь так:
```
Процедура ВыполнитьОбработку() Экспорт
	...
	ВыполнитьРегламентныеДействия_ДиадокПРО(КодОбработки,ДопПараметры);
	...
КонецПроцедуры

Процедура ВыполнитьРегламентныеДействия_ДиадокПРО(КодОбработки, ДопПараметры, АдресХранилища = Неопределено)
	...
	Диадок_ФоновыеЗадания.ВыполнитьКоманду(ДвоичныеДанные,ПараметрыПроцедуры,АдресХранилища);
	...
КонецПроцедуры
```
