### ISSUE TITLE
Как УКД поместить в пакет к УПД

### ISSUE THREAD

**Issue by Namelesssssss** [diadoc/diadoc1cpro-docs#134]
В Контур.EDI или Web версии Диадок при отправке УКД на УПД со статусом "Требуется уточнение", УКД отображается в том же пакете и статус УПД становится "Исправлен". При работе в универсальном модуле в 1С документы отправляются из вкладки "Для отправки", при отправке УКД (иУПД) статус УПД остается "Требуется уточнение" и в пакете ничего не отображается. 
Получается, если на УПД был отправлен УКД, это нигде не отображается и информация о статусе УПД становится некорректной.

Можно ли как-то доработать модуль, чтобы после отправки документ УКД был связан с УПД и в УПД менялся статус?

**Comment by Namelesssssss** [comment]
Версия модуля: 4.17.12.1922

**Comment by NikitaLysenkoA** [comment]
Добрый день. 
Возможности связать пакеты нет.
