### ISSUE TITLE
Добавление тегов в исходящий УПД

### ISSUE THREAD

**Issue by GSAero** [diadoc/diadoc1cpro-docs#136]
Версия модуля 4.23.0.2051, 1С УТ 10.3
Стоит задача - добавить несколько тегов/полей в шапку документа и в каждую строку по товару.
Есть похожий вопрос: https://github.com/diadoc/diadoc1cpro-docs/issues/109 - но на него так и не ответили.
Вот, что нужно:

<img width="547" alt="образец" src="https://user-images.githubusercontent.com/22854138/197701113-215622fe-d6a0-4445-9a60-d8a47d7004b0.png">
![Шапка](https://user-images.githubusercontent.com/22854138/197701420-1c95c53d-d625-4e29-89df-8eaf77efaf64.png)
![Товары](https://user-images.githubusercontent.com/22854138/197701443-4fe58bf7-3dcf-4de7-b151-89643ff021aa.png)

Есть документация: https://developer.kontur.ru/Docs/Diadoc_UM/index.html
Видно я плохо смотрел, но я не нашел, что мне сделать - ни описания, ни примеров.

В общем вопросы:
1) какие события переопределять при генерации подключаемого модуля;
2) какие флаги использовать при генерации подключаемого модуля;
3) что примерно написать в обработчике события.

Было бы здорово, если был бы пример кода.

**Comment by WildSery** [comment]
1. "ПодготовитьЭлектронныйДокумент"
2. не понял, о чём речь
3. для "иных сведений" это Content.TransferInfo.TransferBases, массив, в который можно добавлять структуры типа Новый Структура("DocumentName, DocumentNumber, DocumentDate")
для дополнительных полей в табличной части в массиве Content.Table.Items предусмотрен вложенный массив StructedAdditionalInfos, состоящий из Структура("Key,Value"), например Структура("Key,Value", "код_материала", "338224")

**Comment by GSAero** [comment]
Тех. поддержка ответила с задержкой.
Уже сам давно разобрался.
1С УТ 10.3.75.2.
Доработано событие ПодготовитьПакет в подключаемом модуле.
В общем, см. вложение.
[ПМ_ПодготовитьПакет_ОТР.zip](https://github.com/diadoc/diadoc1cpro-docs/files/10485831/_._.zip)
