### ISSUE TITLE
Заполнение дополнительных данных документа

### ISSUE THREAD

**Issue by milanse** [diadoc/diadoc1cpro-docs#15]
Добрый вечер. 

Используем модуль диадок про в конфигурации Бухгалтерия предприятия корп 3.0
Нужно после типового заполнения основных данных исходящего документа добавить в доп инфо некоторые данные по запросу контрагента.

**Comment by ButurlakinSemyon** [comment]
Добрый день!
Правильно ли я вас понял, что вопрос состоит в том, как заполнить в xml дополнительные сведения?
Если да, то о каких тегах идет речь?
Данные для заполнения известны до отправки документа контрагенту?

**Comment by milanse** [comment]
Нужно добавить инфо в ИнфПолФХЖ1. Данные известны на момент заполнения документа.

**Comment by kulakovskaya** [comment]
Добрый день! Дополнительные сведения (AdditionalInfoId) можно заполнить в подключаемом модуле с помощью функции ПодготовитьЭлектронныйДокумент ().

**Comment by milanse** [comment]
> Добрый день! Дополнительные сведения (AdditionalInfoId) можно заполнить в подключаемом модуле с помощью функции ПодготовитьЭлектронныйДокумент ().

Как мне получить типовое заполнение документа и добавить в него только требуемые дополнительные данные ?

**Comment by kulakovskaya** [comment]
В функции ПодготовитьЭлектронныйДокумент () в строке получаете типовой контент:
![image](https://user-images.githubusercontent.com/54439404/101633314-dfb26980-3a48-11eb-8a35-8a2b5b07ab1d.png)
После можно добавить информацию в дополнительные сведения - [ИнфПолФХЖ1](https://1c-pro-docs.diadoc.ru/ru/latest/objects/Utd820SellerContent.html).

**Comment by MarinaKononchuk** [comment]
Добрый день!
При получении типового контента в подключаемом модуле возникает ошибка при передаче типового модуля методом ТиповойМодульДиадока(). Его нет нигде в описаниях.
Как можно получить указатель на стандартный модуль или что нужно передать в качестве первого параметра функции ОсновнойМодуль.ТиповойМодуль_ПолучитьКонтент()?

**Comment by ButurlakinSemyon** [comment]
@MarinaKononchuk добрый день!
Прошу завести отдельный запрос с более подробным описанием проблемы: используемая версия модуля, какой сценарий необходимо реализовать, текст ошибки.
