### ISSUE TITLE
Как заполнить поля доп. сведений ИнфПолФХЖ2 по номенклатуре в УПД? 

### ISSUE THREAD

**Issue by AleksRiag** [diadoc/diadoc1cpro-docs#153]
Добрый день. В кокой процедуре подключаемого модуля можно сделать и если можно пример реализации заполнения доп. сведений (ИнфПолФХЖ2) по номенклатуре в УПД?(например   <ИнфПолФХЖ2 Идентиф="штрихкод" Значен="4630120123486"/>)

**Comment by acharushkin** [comment]
Привет!

Это можно сделать в событии [ПодготовитьЭлектронныйДокумент](https://developer.kontur.ru/Docs/Diadoc_UM/func/pm/Podgotovit%27ElektronnyyDokument.html)с помощью метода [ДобавитьИнформационноеПоле](https://developer.kontur.ru/Docs/Diadoc_UM/methods/Dobavit%27_Informacionnoe_Pole.html):

```
Контент = Параметры.Content;
Для Каждого Элемент из Контент.Items Цикл

   Штрихкод = ШтрихкодНоменклатуры(Элемент.СлужебнаяИнформация.Номенклатура);
    ОсновнойМодуль.ДобавитьИнформационноеПоле(Элемент, "Идентиф", Штрихкод);

КонецЦикла;
```
(пишу с телефона, возможно с ошибками, но идея, наверное, понятна)
