### ISSUE TITLE
Контур.Диадок Универсальный модуль v4.24.21.2093 не выгружаются файлы отладки.

### ISSUE THREAD

**Issue by aronov-sergey** [diadoc/diadoc1cpro-docs#156]
Добрый день!
Не могу понять причину и проблемы возникающие при попытке выгрузить файлы в режиме отладки.
Отрываем обработку, авторизуемся, жмем на шестеренку, расширенные настройки - системные, разворачиваем Тестирование/отладка, ставим режим отладки, соглашаемся 
![Снимок экрана 2023-01-19 135558](https://user-images.githubusercontent.com/123075296/213426747-b4504f47-ecbb-4f0b-a510-2ad58d0e6f74.png)
Получаю предупреждение о выгрузке файлов и соглашаюсь с ним. Получаю ошибку.
![Снимок экрана 2023-01-19 135628](https://user-images.githubusercontent.com/123075296/213427002-08a43110-3756-4c2e-b765-586055183026.png)
Для выгрузки вложенных обработок, модуль должен быть открыт из каталога, к которому есть доступ для 1с.
сообщения:
{ВнешняяОбработка.КонтурЭДО.МодульОбъекта(4042)}: Ошибка при вызове метода контекста (СоздатьКаталог): Ошибка создания каталога: Ошибка доступа к файлу 'e1cib'. 5(0x00000005): Access is denied.
Не могу понять какой каталог и где именно не может быть создан?
Для какой учетной записи нужно дать разрешение (УЗ сервера 1с дал все права)?
На мой взгляд ошибка доступа к файлу это следствие невозможности создания каталога.
Помогите разобраться, пожалуйста.

**Comment by acharushkin** [comment]
@aronov-sergey , привет!
А модуль ты запускаешь через "Файл - Открыть"?

**Comment by PNK1C** [comment]
Добрый день, была такая же ошибка, помогло следующее:
1. Локальная база
2. Запуск ярлыка от "Администратора", хотя учетка админская, но все-равно именно так ошибка ушла.
