### ISSUE TITLE
Текст в строке 5а. Подключаемый модуль

### ISSUE THREAD

**Issue by PolinaPykh** [diadoc/diadoc1cpro-docs#161]
Генерирую ПМ через плагины для строки 5а (код не меняю). Подключаю через справочник 1С. При попытке открыть счф после подключения ПМ выдает ошибку и я, честно говоря не знаю откуда ее начать решать. Помогите, пожалуйста, возможно вы с этим уже сталкивались?

Несоответствие типов XDTO:
Свойство не может содержать неопределенное значение
{ВнешняяОбработка.КонтурДиадокГенерацияXML.МодульОбъекта(2071)}:		Контент.Значен	 = Параметры.Value;
{ВнешняяОбработка.КонтурДиадокГенерацияXML.МодульОбъекта(12203)}:		Заполнить_ЗначенИдентиф(ТекстИнф, AdditionalInfo);
{ВнешняяОбработка.КонтурДиадокГенерацияXML.МодульОбъекта(9117)}:		XML_ЗаполнитьТекстовуюИнформацию(ИмяПакетаXDTO, ИнфПолФХЖ1.ТекстИнф, Content.AdditionalInfoId.StructedAdditionalInfos);
{ВнешняяОбработка.КонтурДиадокГенерацияXML.МодульОбъекта(7790)}:	XML_УПД_820_ЗаполнитьСведенияСФ(ИмяПакетаXDTO, Документ, ПротоКонтент);
{ВнешняяОбработка.КонтурДиадокЯдро.МодульОбъекта(19015)}:	Результат = Модуль_ГенерацияXML(ЭтотОбъект).XML_ПолучитьXML_УПД_820(ПротоСтруктура, ПараметрыФормированияФайла);
{ВнешняяОбработка.КонтурДиадокЯдро.МодульОбъекта(19113)}:		Результат = ГенерацияXML_УПД820(ПротоКонтентXDTO, ПараметрыГенерацииXML);	
{ВнешняяОбработка.КонтурДиадокЯдро.МодульОбъекта(22911)}:	ДокументXML				= ГенерацияXML_НовыйДокументXML(Документ, ПроверятьXDTO);
{ВнешняяОбработка.КонтурДиадокЯдро.МодульОбъекта(20792)}:				Документы_ЗаполнитьФормализованныйКонтентXML(Документ, ПроверятьXDTO);
{ВнешняяОбработка.КонтурДиадокЯдро.МодульОбъекта(20597)}:	Пакеты_ЗаполнитьМетаданныеДокументов(Результат, Ложь, ПроверятьXDTO);
{ВнешняяОбработка.КонтурДиадокЯдро.МодульОбъекта(20579)}:			Результат = Пакеты_НовыйПакет(СтрокаСписка, ПроверятьXDTO);
{ВнешняяОбработка.КонтурЭДО.Форма.ФормаПакетаУправляемая.Форма(230)}:		Пакет = Ядро.Пакеты_ПодготовитьПакет(Параметры.СтрокаСписка, Ложь);
{(1)}:ОткрытьФорму(ИмяФормы, ПараметрыФормы, Владелец, , , ,  ОписаниеОповещенияОЗакрытии, РежимОткрытияОкна)
{ВнешняяОбработка.КонтурЭДО.Форма.Модуль_СинхронныеМодальныеВызовы.Форма(386)}:			Выполнить("ОткрытьФорму(ИмяФормы, ПараметрыФормы, Владелец, , , ,  ОписаниеОповещенияОЗакрытии, РежимОткрытияОкна)");
{ВнешняяОбработка.КонтурЭДО.Форма.ФормаУправляемая.Форма(362)}:    смв().смв_ОткрытьФорму(ПутьКФормам + мИмяФормы, ПараметрыФормы, Владелец, , , , ОписаниеОповещенияОЗакрытии);
{ВнешняяОбработка.КонтурЭДО.Форма.ФормаУправляемая.Форма(2900)}:	мОткрытьФорму("ФормаПакетаУправляемая", ПараметрыФормы, , ЭтаФорма, КлючПакетаДокументов);
{ВнешняяОбработка.КонтурЭДО.Форма.ФормаУправляемая.Форма(2878)}:			ОткрытьФормуПакета(ВыбраннаяСтрока);

по причине:
Несоответствие типов XDTO:
Свойство не может содержать неопределенное значение

.

**Comment by kontakt59** [comment]
> при генерации указал все галочки

а какие именно галочки указали?

**Comment by kontakt59** [comment]
не могу понять как отрабатывает подключаемый модуль в диадоке.
