### ISSUE TITLE
Доступ к модулю Ядро из ПМ

### ISSUE THREAD

**Issue by NickSemashkin** [diadoc/diadoc1cpro-docs#176]
Необходимо обработать событие в подключаемом модуле "ПолучитьТекстЗапросаДляСпискаПакетовНаОтправкуПоМассивуВидовПакетов", при формировании запроса необходимо учитывать уже отправленные документы. Для добавления в запрос временных таблиц отправленных документов существует функция Ядро.СписокНаОтправку_ТекстЗапроса_ВременныеТаблицы().  При подключении интеграционного модуля типового при инициализации передается две переменные Ядро, ОсновнойМодуль. При подключении ПМ передается только ОсновнойМодуль. Как добраться до ядра из подключаемого модуля? Конфигурация нетиповая, пм пишем полностью с нуля.

**Comment by TulDuRu** [comment]
Держи друг.

![image](https://github.com/diadoc/diadoc1cpro-docs/assets/40054681/f9c74719-6c72-43e5-8ff5-58e488aa9645)


![image](https://github.com/diadoc/diadoc1cpro-docs/assets/40054681/1e0472c7-efb2-428c-89f6-2b72242e26c3)

**Comment by AleksandrVK2024** [comment]
Добрый день, [TulDuRu](https://github.com/TulDuRu)!
Не подскажите, где первый раз вызывается (подключается) ПМ, чтобы один раз инициализировать переменные модуля Ядро и ГенерацияXML?
В интеграционных модулях есть экспортная процедура ИнициализироватьМодуль(), может ее из другого модуля вызвать, "ВызовыПМ", например,
В работе основной обработки и встроенных модулей особо не разбирался, стараюсь ограничиться доработкой ПМ, сделанного из ПМ_БП_30.epf.
