### ISSUE TITLE
Отправка документов ТОРГ2

### ISSUE THREAD

**Issue by NazDaro** [diadoc/diadoc1cpro-docs#177]
Добрый день! 
Можете подсказать, 

реализована отправка **УПД**:
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalTransferDocument", "СЧФДОП", "utd820_05_01_02_hyphen", ИмяФайла);

и **УКД**:
Second_DocumentToSend = SendTask.AddDocumentFromFile("UniversalCorrectionDocument", "КСЧФДИС", "ucd736_05_01_02", ИмяФайла);	

А какие параметры нужны для отправки **ТОРГ2**?
Second_DocumentToSend = SendTask.AddDocumentFromFile("?????????????????????????", "??????", "???????????????", ИмяФайла);

**Comment by dNao75** [comment]
Для ТОРГ-2:
SendTask.AddDocumentFromFile("Torg2", "NoAdditionalInfo", "torg2_05_01_01", ИмяФайла)

**Comment by dNao75** [comment]
NoAdditionalInfo - это если в файле ИнфДопСв=1
а если ИнфДопСв<>1, то видимо надо WithAdditionalInfo - с этим еще не разобрался. Нигде документации нет на этот счет.

**Comment by NazDaro** [comment]
Всё сработало, Спасибо!

**Comment by dNao75** [comment]
Вот что еще выяснил: если отправлять ТОРГ-2 с полем ИнфДопСв=1, то подпись получателя не требуется.
Указал в файле значение поля ИнфДопСв=5 - в этом случае статус документа стал "требуется подпись контрагента", т.е. теперь требуется подписание со стороны получателя.
Как я и предполагал для ИнфДопСв<>1 надо отправлять файл с параметром WithAdditionalInfo. Если пытаться отправить с NoAdditionalInfo, то получим ошибку "Документ не может быть отправлен в указанном формате".

**Comment by dNao75** [comment]
Оказывается, правильный способ запросить подпись получателя - это установить свойство NeedRecipientSignature=True у объекта "документ", который возвращает метод AddDocumentFromFile.
В этом случае не нужны никакие ИнфДопСв=5 и WithAdditionalInfo.
