### ISSUE TITLE
Как указать отпечаток сертификата

### ISSUE THREAD

**Issue by Dina-arts** [diadoc/diadoc1cpro-docs#178]
Как указать в организации ее отпечаток сертификата на сервере? Дописываю подключаемый модуль, там в руководстве пользователя указано, что в настройках организации можно указать её отпечаток на сервере. В последней версии такой настройки не вижу. Дорабатываю модуль для регламентного задания, поэтому отпечаток необходимо получать на сервере. В техподдержке контура мне сказали, что вкладку системные настройки организации можно включить, только с помощью подключаемого модуля.

**Comment by Dina-arts** [comment]
Техническая информация:

Версия модуля: 4.33.0.2492
Версия плагина: 1.5.0.308
Модуль типовой: Да
Система хранения: Типовые объекты 1С
Расположение модуля: ФайлНаДиске
Имя модуля: \\10.195.16.161\share_erp$\Диадок\diadoc_4_33_0.epf
Конфигурация: 1С:ERP Управление предприятием 2 (2.5.12.64)
Модуль интеграции: ПМ_УТ_11

Подключаемый модуль на диске: \\10.195.16.161\share_erp$\Диадок\ДиадокПМ.epf
Тип платформы: Windows x86-64
Версия платформы: 8.3.22.1851
Версия ОС: Microsoft Windows 10 version 10.0  (Build 20348)
Вид клиента: Сервер
Строка соединения: Srvr="rudc1cerpt01.ultires.ru";Ref="ERP_Dev7";
Каталог временных файлов: C:\Users\USR1CV8\AppData\Local\Temp\

Настройки модуля:
Режим прокси: без прокси
Загружать исходящие документы: Да
Загружать входящие документы: Да
Загружать документы только по сопоставленным контрагентам: Нет
Использовать сопоставление подразделений в документах на отправку: Нет
Разрешить фоновые операции: Нет
Сценарий сохранения документов: весь документооборот
Хранить документы на диске: Нет
Загружать документооборот целиком: Нет
Режим логирования: Нет
Режим отладки: Нет
Автообновление модуля: Нет
Отключить контроль дублирования: Нет
Показать количество документов в пакете в разделе "Для отправки": Да
Удалять при переотправке предыдущий документ: Нет
Создавать счета-фактуры: Да
Создавать передаточные документы: Нет
Отключить анализ для входящих документов: Нет
Указывать отсутствие основания УПД: Нет
Отправлять непроведенные документы: Нет
Записывать комментарий при отправке: Нет
Записывать комментарий при создании/сопоставлении: Нет
Использовать сервис "Контур.Маркировка": Нет
HTTP Транспорт: Native

Настройки Стандарта:
Подключаемый модуль : отсутствует
Режим совместимости форматов 155 и 820: Нет

BoxId: 19670d47eafa40b0b0fe2e04e9022968@diadoc.ru
BaseId: 3e2b69ad-1682-46e4-9f85-e41806cb8135
Отпечаток сертификата: Не авторизован
Сертификат: 
Login для обмена: не заполнен
UserId: 7d3e375c-903e-49e3-8628-96d020415b5c

Подключенные библиотеки:
 - ПМ вер. 4 (Макет)
 - ТиповойМодуль вер. 5.57.10.1248 (Макет)
 - ИМ вер. 4 (Макет)
 - ЭмуляторТабДокумента вер. 0.1.0.2 (Макет)
 - Плагин вер. 1.1.21 (Макет)
 - УведомленияПользователей вер. 1.0.2.1 (Макет)
 - КонтурПлагины вер. 3.1.1 (Макет)
 - ХранениеДанных вер. 1.0.0.34 (Макет)
 - ПечатныеФормы вер. 1.5.5.104 (Макет)
 - ВызовыПМ вер. 0.4.2.19 (Макет)
 - ГенерацияXML вер. 4.13.0.150 (Макет)
 - ВнешниеСервисы вер. 0.4.2.4 (Макет)
 - ОсновнойМодуль вер. 4.33.0 (Макет)
 - МенеджерИнтеграции вер. 1.0.0 (Макет)
 - ПарсерJSON вер. 1.0.1.2 (Макет)
 - Ядро вер. 1.1.3.1 (Макет)
 - МетодыAPI вер. 0.1.1.10 (Макет)

Использовать плагины: Да
Установленные плагины:
 - Plugin_PM_builder вер. 0.15.1 (Включен)

**Comment by TulDuRu** [comment]
Доброго времени суток Dina-arts, лично я бы для начал отредактировал ветку так как некоторую информацию не стал бы публиковать в отрытом доступе (BoxId, BaseId, UserId, Имя модуля, Подключаемый модуль на диске)
хотя знание о вашем внутреннем ip адресе ни чего не дает всё же убрал бы, а вот с BoxID и UserId точно нужно по аккуратнее.

Я бы вам помог с вкладкой но не понятно на какой она форме в поддержке не уточнили этот момент ?

**Comment by TulDuRu** [comment]
А ещё я вижу что можно создать доп свойство и не мучатся с этой Вкладкой.

![image](https://github.com/diadoc/diadoc1cpro-docs/assets/40054681/15748157-8160-48c8-a82c-1bfad032b94e)

![image](https://github.com/diadoc/diadoc1cpro-docs/assets/40054681/e727a762-de0e-4151-ae57-560b62bee77a)

![image](https://github.com/diadoc/diadoc1cpro-docs/assets/40054681/2bc2b3a9-bb35-431c-9528-67ed268ffaa1)
