### ISSUE TITLE
Выбранный файл не является подключаемым модулем для модуля Универсальный

### ISSUE THREAD

**Issue by ovt256** [diadoc/diadoc1cpro-docs#179]
Выгрузил из макета ПМ_УТ_11_epf подключаемый модуль, указал путь к нему в Расширенные настройки-Подключаемый модуль.
При запуске Диадока ругается:
Выбранный файл не является подключаемым модулем для модуля Универсальный.
1. Проверьте параметры подключаемого модуля в настройках
2. Проверьте, что выбранный файл не является ПМ для модуля Стандарт. Если вы переходите со Стандарта, то повторно подключать ПМ не нужно. Доработки перенесутся автоматически
Подробности см. в журнале регистрации.

Техническая информация

Версия модуля: 4.33.0.2492
Версия плагина: 1.5.0.308
Модуль типовой: Да
Система хранения: Типовые объекты 1С
Расположение модуля: ЭлементСправочника
Имя модуля: 
Конфигурация: Управление торговлей, редакция 11 (11.5.12.73)
Модуль интеграции: ПМ_УТ_11

Подключаемый модуль на диске: \\stm\c$\Work\PM_Diadoc.epf
Тип платформы: Windows x86-64
Версия платформы: 8.3.23.1688
Версия ОС: Microsoft Windows 8.1 version 6.3  (Build 9600)
Вид клиента: Сервер

Не подскажете в чем бикоз?

**Comment by acharushkin** [comment]
Привет!
У пользователя ОС, от имени которого запущен сервер 1С, есть доступ к файлу ПМ?

**Comment by ovt256** [comment]
Да, безусловно.

**Comment by ovt256** [comment]
Удовлетворяю хотелки клиентов: кому-то в электронном УПД в качестве основания нужен договор, кому-то номер заказа по данным клиента, кто-то просит заполнить Иные сведения нужной ему информацией, кому-то нужны свои коды товаров...
В принципе, ничего, что выходило бы за рамки этого, не требуется. По крайней мере пока.
Пока обошелся генерацией шаблона и использованием его в качестве ПМ.
