### ISSUE TITLE
Название файлов полученных из Диадок по API

### ISSUE THREAD

**Issue by JulyMalysh** [diadoc/diadoc1cpro-docs#199]
Добрый день.
При загрузке файлов по api из Диадок с ЭП. Названия файлов и ЭП приходят без кавычек, буква "й" меняется на "и" или на " " (пробел). Какие еще могут быть изменения в наименовании файлов полученных по API?

Речь про исходящие документы из нашей организации. 
Например отправляем документ с названием:  
Добрый знак.docx 

Получаем от контрагента ЭП:
Добрыи  знак_SGN_1.sgn
и файл:
Добрыи  вестник.docx

**Comment by GilimkhanovDenis** [comment]
Добрый день, я бы проверил, что в имени файла используется `й` (один символ), а не `й` (два символа)

Про отличия можно почитать, например [здесь](https://habr.com/ru/articles/262679/)

Если нужна будет помощь, то уверен, специалисты технической поддержки смогут помочь в этом вопросе,
или нужна хотя бы ссылка на документ, для которого такое поведение воспроизводится (есть вероятность, что до Диадок файлы приходят уже с изменённым именем и тогда причину нужно искать ещё на этапе отправки)
