### ISSUE TITLE
Формирование УПД (СЧФДОП)

### ISSUE THREAD

**Issue by rgkasimov** [diadoc/diadoc1cpro-docs#22]
Добрый день.
Пытаюсь реализовать формирование УПД на основе счет-фактуры и вроде де бы все корректно формируется, но не получается заполнить данные о подписантах. 
Поле "Руководитель организации или иное уполномоченное лицо" и "Ответственный за правильность оформления факта хозяйственной жизни". 
Пытался заполнять данные в Результат.Content.Signers, но при формировании счет фактуры в ДиадокПро, этих данные не вижу.
Заполняю вот так:

`Процедура ОТ_ЗаполнитьSigners(Контент, пДокумент1с)

	// ФИО руководителя организации
	РуководительОрганизации = ПолучитьРеквизитыПодписантаПоОрганизации1С(пДокумент1с.Организация, пДокумент1с.Дата);
	лФамилияРук 	= РуководительОрганизации.Фамилия;
	лИмяРук	 		= РуководительОрганизации.Имя;
	лОтчетствоРук	=РуководительОрганизации.Отчество;
	
	Если ЗначениеЗаполнено(лФамилияРук) Тогда 
		НовЭлемент = НовыйЭлементСпискаXDTO(Контент);		
		
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "JobTitle"	,  РуководительОрганизации.Должность);
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "INN"	, пДокумент1с.Организация.ИНН);
		
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "FirstName", 	лФамилияРук);
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "Surname"	, 		лИмяРук);
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "Patronymic", 	лОтчетствоРук);
		
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "SignerType", "LegalEntity"); // Представитель юридического лица
		
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "Status", "SellerEmployee");		
		УстановитьЗначениеXDTO(НовЭлемент.SignerDetails, "PowersBase", "Должностные обязанности");		
	Иначе
		Сообщить("Ошибка заполнения руководителя организации");
	КонецЕсли;
КонецПроцедуры
`

Когда открываешь в ДиадокПро пакет, он отображается как УПД, но подписей нет.
Подскажите, пожалуйста, как правильно их заполнять? 
Их в УПД несколько штук - Руководитель, Ответственный за заполнение и т.д.

Спасибо.

**Comment by rgkasimov** [comment]
Добрый день.
В процессе отладки выяснил, что в обработке "Ядро.epf" происходит очистка всех подписей в документе.
Происходит это в процедуре 
`Процедура Документы_ЗаполнитьПротоСтруктуруПодписантом(Документ, ПротоСтруктура, Сторона = "Продавец") Экспорт
	
	Если Подписант_ИспользоватьДетальныеДанные(Документ.Тип.ТипКонтента) Тогда                
		
		ExtendedSigner = Подписант_СПолномочиями(Документ, Сторона);
		
		Если ТипЗнч(ПротоСтруктура) = Тип("Структура") Тогда
			ExtendedSigner = ОбъектXDTOВСтруктуру(ExtendedSigner);
		КонецЕсли;
		
		ПротоСтруктура.Signers.Очистить();
		ПротоСтруктура.Signers.Добавить(ExtendedSigner);	
		
	Иначе
		
		Signer = Подписант(Документ.Идентификаторы.BoxId);
		
		Если ТипЗнч(ПротоСтруктура) = Тип("Структура") Тогда
			Signer = ОбъектXDTOВСтруктуру(Signer);
		КонецЕсли;
		
		ПротоСтруктура.Signer = Signer;
		
	КонецЕсли;
	
КонецПроцедуры`
В ней проверяется условие **Подписант_ИспользоватьДетальныеДанные(Документ.Тип.ТипКонтента)**

`Функция Подписант_ИспользоватьДетальныеДанные(ТипКонтента)
	
	Результат = Ложь;
	
	Если НРег(ТипКонтента) = "utd"
		Или НРег(ТипКонтента) = "utd820"
		Или НРег(ТипКонтента) = "ucd"
		Или НРег(ТипКонтента) = "rezru"
		Или НРег(ТипКонтента) = "tovtorg" Тогда
		
		Результат = Истина;
		
	КонецЕсли;
	
	Возврат Результат;
	
КонецФункции`
Так как в моем УПД ТипКонтента =  "utd820", то подписи очищаются.

Возникает вопрос, Их вообще невозможно заполнить в УПД или заполнять их нужно как-то по другому?

**Comment by volodkindv** [comment]
Добрый день.
Данные подписанта модуль заполняет автоматически по данным сертификата, под которым авторизован пользователь. Их не нужно заполнять.

**Comment by rgkasimov** [comment]
> Добрый день.
> Данные подписанта модуль заполняет автоматически по данным сертификата, под которым авторизован пользователь. Их не нужно заполнять.

Спасибо.
