### ISSUE TITLE
Открытие формы отправки документа 

### ISSUE THREAD

**Issue by milanse** [diadoc/diadoc1cpro-docs#23]
Подскажите, есть ли какая-то возможность работать с модулем не через форму диадок-про. 

Например сделать в документе кнопку - Отправить в диадок, жму ее - открывается форма с заполненным документом.

**Comment by IrinaShmonina** [comment]
@milanse, здравствуйте,
К сожалению, такой возможности нет, но мы зафиксировали ваше пожелание

**Comment by milanse** [comment]
> @milanse, здравствуйте,
> К сожалению, такой возможности нет, но мы зафиксировали ваше пожелание

Вообще не хватает более низкоуровневого интерфейса для взаимодействия с подсистемой. Получается или ты сильно ограничен существующим интерфейсом Диадок ПРО или все делаешь сам без возможности использовать функции ядра по работе с контентом, отправке и получению данных.

**Comment by ButurlakinSemyon** [comment]
Пожелание зафиксировано. Спасибо за ваше мнение. 
Этот запрос закрываю, при возникновении вопросов прошу создавать новый.
