### ISSUE TITLE
Модуль ПРО: сертификат на сервере 1С

### ISSUE THREAD

**Issue by Hugador** [diadoc/diadoc1cpro-docs#24]
Добрый день.
У нас подготовка ответов на вх. документы (Подписать, Отказать, Запросить уточнение)  выполняется регламентным заданием по результатам согласования документов в учетной системе. Отправку осуществляет пользователь 1С по кнопке "Отправить готовые ответы". 
При подготовке ответов система требует авторизацию по сертификату - в коде есть проверка в процедуре "Документы_ВариантыОтветныхДействий",  нам пришлось установить тестовый сертификат на сервер 1С.  
Теперь переходим в рабочую эксплуатацию и руководство интересуется - какой (чей) рабочий сертификат ставить на сервер и для чего он нужен?  Какую роль он играет в подписании вх. документов, если отправляет подготовленные ответы на документы человек интерактивно? Чья подпись в итоге будет на вх. документах -  серверного сертификата или того, кто отправлял готовые ответы?

**Comment by ButurlakinSemyon** [comment]
Добрый вечер! Для более корректного ответа на ваш вопрос необходимо взглянуть на подключаемый модуль. Можете его прислать?

**Comment by Hugador** [comment]
Да, конечно. Не вижу кнопку для вложений, прикладываю ссылку на модуль на Гугл-диске:
https://drive.google.com/file/d/1YqWL6axbCn85GhHUg4ZwFn8hsOApIE14/view?usp=sharing

**Comment by Hugador** [comment]
Есть еще вопрос по этому модулю - раз он уже у вас)
Посмотрите пож. в процедуру "ПолучитьТаблицуИспользуемыхВидовДокументов" - там есть две строки:
```
ОсновнойМодуль.ЭДО_Служебные_ДобавитьСтрокуВТаблицуЗначений(ТЗ, артДиадок.Строка_ID_УКД(),  "УКД", 		 артДиадок.Строка_UniversalCorrectionDocument(), 	     артДиадок.Строка_ucd(),    артДиадок.Строка_КСЧФДИС());
	
//	Для формализованных корректировочных Актов и корректировочных ТОРГ12 можно использовать только УниверсальныйКорректировочныйДокумент.
	ОсновнойМодуль.ЭДО_Служебные_ДобавитьСтрокуВТаблицуЗначений(ТЗ, артДиадок.Строка_ID_УКД(), "Акт/ТОРГ-12 корр.", артДиадок.Строка_UniversalCorrectionDocument(), артДиадок.Строка_ucd(), артДиадок.Строка_ДИС());
```
Они сути нам нужны (если я правильно понимаю), но некорректно отрабатывают при сопоставлении типов АПИ в модуле - появляются дубли в настройках модуля (где сопоставление) и в списке на отправку, т.к. создаются два элемента в справочнике "Диадок_ДополнительныеСправочники": 
![image](https://user-images.githubusercontent.com/72465175/107794021-fdad8a80-6d67-11eb-8abd-5a6a119073d5.png)

**Comment by volodkindv** [comment]
По изначальному вопросу в тикете:
При действии "Отправить готовые ответы" титулы подписываются сертификатом, установленным &НаКлиенте.
В коде ПМ у вас также есть отправка извещений о получении в "артСформироватьОтправитьИзвещенияОПолученииСчетовФактур". Вот они подписываются сертификатом, установленным &НаСервере.

**Comment by volodkindv** [comment]
По второму вопросу: дубли возникают из-за одинаковых ID.
`артДиадок.Строка_ID_УКД()`
Сделайте их разными.

Желательно оформлять разные вопросы разными тикетами, иначе ответы перемешиваются и сложно потом разобраться.

**Comment by Hugador** [comment]
> По изначальному вопросу в тикете:
> При действии "Отправить готовые ответы" титулы подписываются сертификатом, установленным &НаКлиенте.
> В коде ПМ у вас также есть отправка извещений о получении в "артСформироватьОтправитьИзвещенияОПолученииСчетовФактур". Вот они подписываются сертификатом, установленным &НаСервере.

Спасибо.  
Нужно все-таки уточнить: если при нажатии на кнопку "Отправить готовые ответы" документы подписываются клиентским сертификатом, то для чего система требует сертификат на сервере при подготовке этих ответов в регламентном задании? Именно этот момент интересует руководство - какова роль этого сертификата при подготовке ответов?

**Comment by volodkindv** [comment]
> для чего система требует сертификат на сервере при подготовке этих ответов в регламентном задании?

Как это требование проявляется? Опишите подробнее.
Сейчас в коде:

```
Функция ВыполнитьРегламентныеДействия(Параметры = Неопределено) Экспорт 	
	
	...
		// Стандартные действия для рег. задания "Диадок_РегламентныеДействия"
		артЗагрузитьЛентуСобытий();   // достаточно авторизации под логином
		артСформироватьОтправитьИзвещенияОПолученииСчетовФактур();  // здесь действительно нужна авторизация под сертификатом
		артОбработатьОчередьНаСозданиеДокументов1С();  		// здесь авторизация не нужна
		артПодготовитьОтветыПоДокументам();  // здесь внутри есть авторизация под сертификатом, но она не нужна
```

**Comment by Hugador** [comment]
Писала в начальном обращении:
"При подготовке ответов система требует авторизацию по сертификату - в коде есть проверка в процедуре "Документы_ВариантыОтветныхДействий""
Во всяком случае, на тот момент (в том релизе) было актуально. Мы тогда не формировали извещения по с/ф и операция подготовки ответов первая вынудила на сертификат на сервер поставить, я сначала пробовала обойтись без него.

**Comment by volodkindv** [comment]
Теперь понятно, речь про этот блок:
```
Функция артПодготовитьОтветыПоДокументам(Документ1С = Неопределено)
	
...			
			СписокДопустимыхОтветныхДействий = ОсновнойМодуль.ЭДО_ВариантыОтветныхДействийПоДокументу(ДокументДД);
			
			Если СписокДопустимыхОтветныхДействий.НайтиПоЗначению(Вердикт) = Неопределено Тогда			
```
Этот метод действительно проверяет, авторизован ли текущий пользователь под сертификатом. Метод используется для переключения доступности кнопок с действиями в пользовательском интерфейсе модуля. В вашем случае можно, например, проверять значение поля "Статус" справочника "Диадок_Документы". Если там "Ожидается подпись контрагента", тогда готовить ответ. Или оставить как есть, если в соседнем коде все равно происходит авторизация по сертификату. В любом случае для подписания будет использоваться сертификат конкретного пользователя, который работает с модулем.

**Comment by Hugador** [comment]
Понятно, спасибо.
Использование данного кода видела в примерах ПМ от ваших коллег или на вашем сайте вики, поняла, что так положено делать для подготовки ответов. Хотелось бы использовать максимально универсальные процедуры (черные ящики) для упрощения дальнейшего сопровождение ПМ.

**Comment by volodkindv** [comment]
Действительно, пример можно найти в документации: [вот он](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Obrabotka_Vkhodyashchikh_Paketov.html?highlight=%D1%8D%D0%B4%D0%BE_%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82%D1%8B%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BD%D1%8B%D1%85%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B9%D0%BF%D0%BE%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%83).
Спасибо за замечание. Обновлением документации мы займемся позже.
