### ISSUE TITLE
Параметры вызова функции ПолучитьТекстЗапросаДляСпискаПакетовНаОтправкуПоМассивуВидовПакетов

### ISSUE THREAD

**Issue by vsbronnikov** [diadoc/diadoc1cpro-docs#27]
В новой версии модуля ДиадокПро 4.4 (4.4.0.834) изменились параметры вызова функции "ПолучитьТекстЗапросаДляСпискаПакетовНаОтправкуПоМассивуВидовПакетов" подключаемого модуля. В документации написано, что параметр "Параметры.МассивВидовПакетов" - это массив ссылок на виды пакетов. А сейчас это массив ID видов пакета. Это поведение не соответствует документации.
Как правильно:
1. Массив ссылок - и тогда это ошибка релиза 4.4? 
2. Массив ID - тогда нужно поправить документацию?

**Comment by ButurlakinSemyon** [comment]
Добрый день. 
Действительно, в версии 4.4 изменились параметры вызова функции. Правильным будет массив ID.
Документацию обязательно актуализируем..
