### ISSUE TITLE
Получение списка документов при фоновом задании

### ISSUE THREAD

**Issue by cmd-belkevich** [diadoc/diadoc1cpro-docs#30]
Добрый день, не могли бы вы подсказать, каким образом возможно получить список входящих документов в подключаемом модуле, при выполнении регламентного задания?
В Функции ВыполнитьРегламентныеДействия приходит пустая структура параметры, а в переменной ОсновнойМодуль приходит пустая таблица СпискаДокументов.
При выполнении других событий подключаемого модуля параметры приходят с заполненным данными таблицы списка документов.

Версия модуля: 4.4.0 
Версия плагина: 1.2.2.173 
Версия платформы: 8.3.16.1296 
Версия ОС: Microsoft Windows 7 version 6.1 Service Pack 1 (Build 7601) 
Тип платформы: Windows x86 
Вид клиента: Толстый клиент обычное приложение  
Подключаемый модуль в конфигурации: ПмДиадок 
Конфигурация: Управление производственным предприятием, редакция 1.2 (1.2.32.1) 
Для наглядности скриншот во вложении. Спасибо.
![СписокДокументовДляДИАДОК](https://user-images.githubusercontent.com/81566091/112833053-d6ecae80-909e-11eb-8fb9-c49693f3f055.jpg)

**Comment by IrinaShmonina** [comment]
Можно попробовать следующий код:

`
Если НЕ ЗначениеЗаполнено(УчетнаяЗапись().Логин) Тогда

	Сообщить("Не указана служебная учетная запись для выполнения регламентных действий.");
	Возврат Ложь;
КонецЕсли;

// АВТОРИЗАЦИЯ ПО ЛОГИНУ И ПАРОЛЮ 

ОсновнойМодуль.ЭДО_АвторизоватьсяПодЛогином(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль);
// или авторизация по сертификату на сервере
//ОсновнойМодуль.ЭДО_АвторизоватьсяПодСертификатомНаСервере1С();

КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();

ПараметрыОбновленияСписка = Новый Структура;
ПараметрыОбновленияСписка.Вставить("Режим",					"ПолученныеДокументы");
ПараметрыОбновленияСписка.Вставить("НачалоПериода",			ДобавитьМесяц(ТекущаяДата(), -1));
ПараметрыОбновленияСписка.Вставить("КонецПериода",			КонецДня(ТекущаяДата()));
ПараметрыОбновленияСписка.Вставить("ПоказыватьЗавершенные",	Ложь);

Для Каждого Элемент Из КонтекстСеанса Цикл
	
	СтрокаКонтекста	 = Элемент.Значение;
	Организация		 = СтрокаКонтекста.ОрганизацияДиадок.СвязанныйСправочник1;
	
	ПараметрыОбновленияСписка.Вставить("ОтборПоОрганизации", Организация);
	
	ОсновнойМодуль.ЭДО_Модуль_ОбновитьСписокДокументов(ПараметрыОбновленияСписка);
	
	Для Каждого СтрокаТЧ Из ОсновнойМодуль.СписокДокументов Цикл
		
		// обработка документа
		
	КонецЦикла;
	
КонецЦикла;`

Более подробнее в [документации](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html)

**Comment by cmd-belkevich** [comment]
> @cmd-belkevich, здраствуйте
> Можно попробовать следующий код:
> 
> > Если НЕ ЗначениеЗаполнено(УчетнаяЗапись().Логин) Тогда
> > Сообщить("Не указана служебная учетная запись для выполнения регламентных действий.");
> > Возврат Ложь;
> > КонецЕсли;
> > // АВТОРИЗАЦИЯ ПО ЛОГИНУ И ПАРОЛЮ
> > ОсновнойМодуль.ЭДО_АвторизоватьсяПодЛогином(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль);
> > // или авторизация по сертификату на сервере
> > //ОсновнойМодуль.ЭДО_АвторизоватьсяПодСертификатомНаСервере1С();
> > КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();
> > ПараметрыОбновленияСписка = Новый Структура;
> > ПараметрыОбновленияСписка.Вставить("Режим",					"ПолученныеДокументы");
> > ПараметрыОбновленияСписка.Вставить("НачалоПериода",			ДобавитьМесяц(ТекущаяДата(), -1));
> > ПараметрыОбновленияСписка.Вставить("КонецПериода",			КонецДня(ТекущаяДата()));
> > ПараметрыОбновленияСписка.Вставить("ПоказыватьЗавершенные",	Ложь);
> > Для Каждого Элемент Из КонтекстСеанса Цикл
> > СтрокаКонтекста	 = Элемент.Значение;
> > Организация		 = СтрокаКонтекста.ОрганизацияДиадок.СвязанныйСправочник1;
> > ПараметрыОбновленияСписка.Вставить("ОтборПоОрганизации", Организация);
> > ОсновнойМодуль.ЭДО_Модуль_ОбновитьСписокДокументов(ПараметрыОбновленияСписка);
> > Для Каждого СтрокаТЧ Из ОсновнойМодуль.СписокДокументов Цикл
> > ```
> >   // обработка документа
> > ```
> > 
> > 
> > КонецЦикла;
> > КонецЦикла;
> 
> Более подробнее в [документации](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html)

Добрый день, спасибо за ответ, но ситуация не изменилась. 
![Диадок СписокДокументов](https://user-images.githubusercontent.com/81566091/114168448-f0141b80-9938-11eb-8f9c-d2d1f8b403fa.jpg)
![Диадок Контекст Сеанса](https://user-images.githubusercontent.com/81566091/114168454-f0acb200-9938-11eb-9449-b38c00576584.jpg)

**Comment by IrinaShmonina** [comment]
@cmd-belkevich , добрый день
Проверьте, действительно ли авторизация проходит успешно под указанными логином и паролем. 

Приведенный выше пример достаточно типовой.

**Comment by cmd-belkevich** [comment]
> @cmd-belkevich , добрый день
> Проверьте, действительно ли авторизация проходит успешно под указанными логином и паролем.
> 
> Приведенный выше пример достаточно типовой.

Авторизация при запуске в обычном режиме(по этому логин/паролю) проходит успешно, в фоновом задании происходить получение токена, что как я понимаю указывает на успешность авторизации. Но далее в процедуре модуля Ядра:
Функция КонтекстСеанса_СтрокиКонтекста(ДобавитьНеоплаченные = Ложь) Экспорт
	
	Результат = Новый Соответствие;
	
	ХранилищеКонтекста = ХранилищеКонтекстаСеанса();//соответствие во вложении
	
	Если ЗначениеЗаполнено(ХранилищеКонтекста) Тогда //истина
		
		Для Каждого КлючИЗначение Из ХранилищеКонтекста Цикл
			
			СтрокаКонтекста = КлючИЗначение.Значение;
			
			ТребуетсяОплатаСервиса		 = СтрокаКонтекста.ТребуетсяОплатаСервиса;
			ЭтоСлужебнаяУчетнаяЗапись	 = Не ЗначениеЗаполнено(СтрокаКонтекста.BoxId); //истина
			//добавление в результат не происходит из-за проверки "И Не ЭтоСлужебнаяУчетнаяЗапись = ложь"

			Если (Не ТребуетсяОплатаСервиса Или ДобавитьНеоплаченные) И Не ЭтоСлужебнаяУчетнаяЗапись Тогда
				
				Результат.Вставить(КлючИЗначение.Ключ, КлючИЗначение.Значение);
				
			КонецЕсли;
			
		КонецЦикла;
		
	КонецЕсли;
	
	Возврат Результат;
	
КонецФункции

Необходимо наличие какой то другой учетной записи?
![Диадок_ХранилищеКонтекстаСеанса](https://user-images.githubusercontent.com/81566091/115220754-974f3a80-a111-11eb-8f72-628665b239eb.jpg)

**Comment by IrinaShmonina** [comment]
@cmd-belkevich , надо заполнить список доступных организаций, для которых будет формироваться список. 

После авторизации попробуйте добавить заполнение контекста для служебной учетки. 

ОсновнойМодуль.ЭДО_АвторизоватьсяПодЛогином(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль); ОсновнойМодуль.ЭДО_ЗаполнитьКонтекстСеансаДляСлужебнойУчетнойЗаписи();

....

**Comment by cmd-belkevich** [comment]
> @cmd-belkevich , надо заполнить список доступных организаций, для которых будет формироваться список.
> 
> После авторизации попробуйте добавить заполнение контекста для служебной учетки.
> 
> ОсновнойМодуль.ЭДО_АвторизоватьсяПодЛогином(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль); ОсновнойМодуль.ЭДО_ЗаполнитьКонтекстСеансаДляСлужебнойУчетнойЗаписи();
> 
> ....

Попробовал, ситуация не изменилась

**Comment by kulakovskaya** [comment]
Здравствуйте. Для решения проблемы требуется удаленное подключение. Для организации данного процесса обратитесь в [техподдержку](https://www.diadoc.ru/support) любым удобным способом.

**Comment by IrinaShmonina** [comment]
@cmd-belkevich , здравствуйте
При заполнении контекста сеанса для служебной учетной записи у вас не происходит заполнение поля "ОрганизацияДиадок". Для получения связанной организации 1С необходимо сделать следующие изменения


	Для Каждого Элемент Из КонтекстСеанса Цикл
	
	СтрокаКонтекста = Элемент.Значение;

	// заменить эту строку
	Организация = СтрокаКонтекста.ОрганизацияДиадок.СвязанныйСправочник1;
	// на эту
	Организация = ОсновнойМодуль.СопоставленнаяОрганизацияВ1С(СтрокаКонтекста.BoxId);
	
	ПараметрыОбновленияСписка.Вставить("ОтборПоОрганизации", Организация);
	
	ОсновнойМодуль.ЭДО_Модуль_ОбновитьСписокДокументов(ПараметрыОбновленияСписка);
	
	Для Каждого СтрокаТЧ Из ОсновнойМодуль.СписокДокументов Цикл
		
		// обработка документа
		
	КонецЦикла;
	
	КонецЦикла;

**Comment by cmd-belkevich** [comment]
> 

Спасибо, это помогло.
