### ISSUE TITLE
Диадок Про отладка. Проблемы.

### ISSUE THREAD

**Issue by Olga5577** [diadoc/diadoc1cpro-docs#31]
Опять появилась проблема с отладкой модулей Диадок Про.  Модули выгружены в каталог libs рядом с основным модулем. Ставлю точки останова, в них попадаю в выгруженные модули (просто анализирую код для понимания. Далее надо будет писать свой подключаемый модуль). Все было нормально, все точки останова срабатывали, вдруг в какой-то момент по непонятной причине перестали видеться точки останова в модуле Ядро.epf.   Те самые, что срабатывали раньше. В модуль Ядро.epf пшаговая отладка теперь не переходит. В чем может быть дело?

За день или два до этого 1С зависал при работе с Диадоком, пришлось закончить сеансы через консоль администрирования серверов 1С. Возможно, что-то сбилось при этом? Как восстановить срабатывание точек останова в Ядро.epf? Какой-то кеш влияет, что-то еще?

**Comment by IrinaShmonina** [comment]
Дубль https://github.com/diadoc/diadocapi-docs/issues/766. Вопрос задала в этом обращении
