### ISSUE TITLE
Выбор типа создаваемого документа

### ISSUE THREAD

**Issue by milanse** [diadoc/diadoc1cpro-docs#32]
Подскажите как использовать эту фичу ? 
У меня несколько видов документов, которые можно создать из входящего акта и СФ, вижу есть функционал, не понятно как его использовать. Функцию _СписокТиповДокументовДляСоздания_ добавил, она вызывается, но не отображается выбор типа на кнопке. 

Как выбранный тип документа можно использовать в процедуре поиска и заполнения документа 1С ?

**Comment by kulakovskaya** [comment]
Здравствуйте! В [документации](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Obrabotka_Vkhodyashchikh_Paketov.html#id4) описана логика создания документов с выбором типа.

**Comment by milanse** [comment]
У меня не показывается список выбора вида документа:

Выбор вида документа
При нажатии на кнопку «Создать» из формы пакета пользователю предоставляется выбор - какой именно документ 1С создавать. Для управляемых форм есть предопределенный список видов документов, которые зависят от конфигурации. Список можно редактировать в событии СписокТиповДокументовДляСоздания.

Хотя функция ПМ вызывается, может устаревший модуль диадок про (Версия модуля: 4.4.17.846) ? Он не не формирует структуру ПМ в формате 3

**Comment by kulakovskaya** [comment]
Подскажите, какая у Вас конфигурация 1С?

**Comment by milanse** [comment]
Конфигурация своя не типовая на УФ.

**Comment by milanse** [comment]
Сорян , понял в чем проблема. Список типов появился. Я правильн понимаю что формат ПМ 3 отличается от 2 только наличием функции СписокТиповДокументовДляСоздания ?

**Comment by kulakovskaya** [comment]
Да, правильно.

**Comment by milanse** [comment]
Я так понимаю из списка документов не получится заполнить входящий, т.к. нет возможности выбора.
