### ISSUE TITLE
Вывод подробной информации о причине ошибки

### ISSUE THREAD

**Issue by milanse** [diadoc/diadoc1cpro-docs#33]
В качестве пожелания, хотелось бы видеть более подробную информацию об ошибке. 

В карточке документа диадок жму перезаполнить, выскакивает плашка, что заполнить не удалось, на этом все.

**Comment by IrinaShmonina** [comment]
@milanse , здраствуйте,
уточните, пожалуйста, версию модуля

**Comment by milanse** [comment]
Версия модуля: 4.4.17.846
Думаю ошибка там на этапе взаимодействия с порталом, при перезаполнении пытается перенести документ на поратле в папку удаленные и что-то идет не так. Техподдержка на такие обращения рекомендует удалять документы в данных 1С руками.

**Comment by IrinaShmonina** [comment]
@milanse , добрый день
Вам нужно будет связаться с нашей технической поддержкой - https://www.diadoc.ru/support

**Comment by milanse** [comment]
Дак я сюда и пришел из технической поддержки ) их совет - чистить все руками и заполнять документ по новой. Ну и на обращение поддержка попросит описание ошибки, а все описание, это то что не удалось выгрузить. Что тп с этим может сделать?

**Comment by IrinaShmonina** [comment]
Можете дать инн-кпп?

**Comment by milanse** [comment]
Вот для примера, пакет заполнили, отправили на согласование, в согласовании отказано, нужно скорректировать пакет.

Пользователь хочет перезаполнить пакет добавить / убрать документы, жмет перезаполнить, в ответ - не удалось перезаполнить. 

смотрим кишки: 

![image](https://user-images.githubusercontent.com/15941393/117938448-bb1c2f80-b30f-11eb-88ce-11e75320b0cf.png)

Я так понимаю, если метка "Отправлен" - молча не перезаполняет ? 

Можно как-то сообщать - "Пакет уже отправлен, нельзя перезаполнить" или убрать кнопку перезаполнить на форме ? 

Ну и наверное отказанные в подписи / в согласовании пакеты можно перезаполнять ?

**Comment by ButurlakinSemyon** [comment]
Добрый день. 
Можете прислать подключаемый модуль?

**Comment by milanse** [comment]
[ДД_ПодклМод.bsl.zip](https://github.com/diadoc/diadoc1cpro-docs/files/6636687/_.bsl.zip)

Положил.

**Comment by GordanovaKseniya** [comment]
@milanse, добрый день!
Можете прислать ваш boxId или ИНН-КПП.

**Comment by milanse** [comment]
Открыл еще одну ишью #53 
ИНН: 7714550531
КПП: 773601001

**Comment by GordanovaKseniya** [comment]
@milanse Добрый день!
Перезаполнение не срабатывает на каких-то конкретных видах пакетов или вообще по всем видам?
