### ISSUE TITLE
Запуск регламентного задания по расписанию

### ISSUE THREAD

**Issue by Olga5577** [diadoc/diadoc1cpro-docs#36]
Вопрос по поводу регламентного задания.
При выполнении регламентного задания выполняются функции подключаемого модуля. Функции написаны.
Вопрос - как настроить расписание регламентного задания, если оно находится на поддержке, не редактируется и нет доступа ни к его расписанию, ни к другим его свойствам?

**Comment by Olga5577** [comment]
снимать с поддержки, писать еще одно?

**Comment by kulakovskaya** [comment]
Здравствуйте!
Какую версию модуля используете? Если есть возможность, то приложите тех.информацию из модуля.
Опишите подробнее с какой проблемой столкнулись.

**Comment by Olga5577** [comment]
версия 4-4-0 диадок про.
Собственно, описывать подробно нечего. Просто вопрос-  как настроить расписание регламентного задания диадока. Чтобы оно выполнялось периодически.

**Comment by Olga5577** [comment]
не по кнопке "Выполнить регламентные действия", а периодически без участия пользователя

**Comment by Olga5577** [comment]
Техническая информация:

Версия модуля: 4.4.0.834
Версия плагина: 1.2.2.173
Модуль типовой: Нет
Конфигурация: 1С:ERP Управление предприятием 2 (2.4.11.71)
База серверная
Модуль интеграции: ПМ_УТ_11
Подключаемый модуль на диске (пока. потом будет встроен как дополнительная внешняя обработка)
...
Настройки модуля:
Режим прокси: без прокси
Загружать исходящие документы: Да
Загружать входящие документы: Да
Загружать документы только по сопоставленным контрагентам: Да
Разрешить фоновые операции: Да
Сценарий сохранения документов: 
Хранить документы на диске: Да
Загружать документооборот целиком: Да
Использовать типовые объекты 1С: Нет
Режим логирования: Нет
Отключить контроль дублирования: Нет
Разворачивать пакеты на отправку по документам: Нет
Показать количество документов в пакете в разделе "Для отправки": Да
Отключить анализ для входящих документов: Нет

**Comment by kulakovskaya** [comment]
Про запуск регламентного действия подробнее можно почитать в [документации](https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html).

**Comment by Olga5577** [comment]
она уже прочитана. И из нее непонятно , к сожалению, как настроить регламентное задание по расписанию.
