### ISSUE TITLE
Получить подпись контрагента

### ISSUE THREAD

**Issue by Olga5577** [diadoc/diadoc1cpro-docs#43]
Добрый день!
Работаем с модулем Диадок Про в Ерп ( есть и свои доработки в подкл.модуле)
Вопрос связан с подписью контрагента.
Отправляем документ контрагенту через Диадок Про в 1С, затем он у себя его подписывает. Мы по кнопке ОБмен с сервером видим изменение статуса документа на "Подписан контрагентом".
Вопрос  - можно ли как-то вытащить подпись контрагента в коде?
При подписи и  отправке документа контрагенту наша подпись, к примеру, формируется  в коде в
Документ.Документооборот.ХранилищеКонтента.Подпись.ДанныеПодписи.
Есть ли возможность получить подпись контрагента в коде в каком-то виде (двоичные данные, файл с его подписью, др.)? Нам это нужно для дальнейших наших доработок.

**Comment by kulakovskaya** [comment]
Добрый день! Уточните версию модуля Про.

**Comment by Olga5577** [comment]
Про версия 4-4-0

**Comment by GordanovaKseniya** [comment]
Добрый день!
Варианты получения подписи контрагента:
1. Присоединенную подпись (.sgn) можно получить напрямую с сервера ДД при получении события (кнопка "Обмен с сервером")

ДвоичныеДанныеПодписи = Модуль_МетодыAPI(ЭтотОбъект).DD_API_GetEntityContent(ПараметрыСервиса, BoxId, LetterId, ДанныеСобытия.Event.Document.Docflow.RecipientResponse.Signature.Cms.EntityId);

2. В справочнике "Диадок: Дополнительные справочники" в элементе "ОбщиеНастройки" в таблицу добавить настройку:
Имя реквизита = ЗагружатьДокументооборотЦеликом
Значение (булево) = Да
![940](https://user-images.githubusercontent.com/84762976/124542991-e0c04380-de3d-11eb-86c4-052fe564158c.png)
Тогда данные подписи можно получить следующим способом:
Идентификаторы = Контракт_Идентификаторы();
 ЗаполнитьЗначенияСвойств(Идентификаторы, ДанныеСобытия);
 Данные = ХранениеДанных_ДанныеХранилища(Идентификаторы,"ПодписьПокупателя");
 ДвоичныеДанныеПодписи = Данные.Подпись.ДанныеПодписи;

**Comment by Olga5577** [comment]
Спасибо
