### ISSUE TITLE
Как в подключаемом модуле обратиться к функциям модуля Ядра?

### ISSUE THREAD

**Issue by Olga5577** [diadoc/diadoc1cpro-docs#46]
Добрый день.
Как в подключаемом модуле обратиться к функциям модуля Ядра?
Нужны функции как серверные, так и клиентские.

**Comment by Olga5577** [comment]
Используем Diadoc Pro 4-4-0

**Comment by Olga5577** [comment]
И как обратиться к  самой основной обработке Диадок для вызова ее функций?

**Comment by volodkindv** [comment]
Добрый день.
Вызов функций Ядра и основной обработки из подключаемого модуля недоступен. Из ПМ доступны только вызовы специальной прослойки - "ВызовыПМ". Это сознательное ограничение, направленное на обеспечение совместимости старых ПМ с новыми версиями модуля.
В основной обработке и в ядре мы иногда меняем сигнатуру методов и сами методы. Если эти методы будут доступны в ПМ, то мы не сможем обеспечить работоспособность клиентских ПМ при обновлениях.

**Comment by Olga5577** [comment]
спасибо, понятно
