### ISSUE TITLE
Не корректно работает метод GetDocumentEventList 

### ISSUE THREAD

**Issue by Kurt-kmr** [diadoc/diadoc1cpro-docs#5]
Здравствуйте. Использую работу через com DiadocInvoiceAPI получаю документы с помощью GetDocumentEventList каждый раз запоминаю ид события и затем получаю документы с него. Но периодически получаются документы 2014г. т.е. те по которым не должно быть событий в 20ом. 
К примеру 07.09.2020 по организации ИНН 2221119456 КПП 222101001 запустил получение документов с события "05806dd6-ece3-4bf2-a2b0-8444b67f3353" пришли нужные документы и последнее событие было "c5b6c9da-f26f-4d6f-9210-c02ab4d7f34b". Далее запустил получение с события "c5b6c9da-f26f-4d6f-9210-c02ab4d7f34b" и посыпались события по документам за 2014год.

**Comment by kulakovskaya** [comment]
Добрый день! Уточните, пожалуйста, версию компоненты. 
А также можете ли предоставить код, который используете для выгрузки документов?

**Comment by Kurt-kmr** [comment]
Разобрался. У меня была проблема. Извиняюсь за беспокойство
