### ISSUE TITLE
Можно ли обновлять статусы документов автоматически

### ISSUE THREAD

**Issue by Olga5577** [diadoc/diadoc1cpro-docs#56]
Добрый день!
Диадок Про 4.5.18 в ерп.
Для обновления статусов исходящих документов (с "требуется подпись контрагента" на "подписан контрагентом", например) нужно выполнять обмен с сервером (кнопка на основной форме).
Можно ли в регламентном задании по расписанию делать обновление этих статусов? Мы используем регламентное задание свое в подключаемом модуле.
В документации я не нашла, какой функцией это можно сделать обновление статусов. Подскажите, пожалуйста.

**Comment by volodkindv** [comment]
Добрый день.
Примеры можно найти здесь: https://1c-pro-docs.diadoc.ru/ru/latest/proc/pm/Reglamentnoye_Zadaniye.html
"Пример получения новых событий и отправка документов" - в этом процессе загружаются новые документы и обновляются статусы существующих.

**Comment by Olga5577** [comment]
Спасибо. Буду разбираться
