### ISSUE TITLE
не заполняется графа "к платежно-расчетному документу" в печатной форме УПД

### ISSUE THREAD

**Issue by Olga5577** [diadoc/diadoc1cpro-docs#59]
добрый день.
работали с диадок про 4.5.18. в ерп . ОБновили Диадок на 4.5.29. Перед этим обновили ерп с 2.11 на 2.13.
Есть свои пакеты в подключаемом модуле. В некоторых из них формируем стандартный УПД диадока. 
В этих пакетах в печатной форме УПД не печатается  графа "к платежно-расчетному документу". 
Вопрос 1. Верно ли , что эта графа заполняется Диадоком из табличной части "ПлатежноРасчетныеДокументы"  документа Счет-фактура? или вытаскивает платежные документы для этой графы как-то по-другому?

**Comment by Olga5577** [comment]
есть ли возможность вместо типового заполнения УПД в Диадоке прицепить типовую печатную форму из 1С, где графа заполняется? если да, подскажите плиз как

**Comment by kab1k** [comment]
Добрый день.

Платежно-расчетные документы берутся из документа счет-фактура, поле "Платежно-расчетные документы". 
1С берет информацию о платежах из регистра, поэтому они отображаются в ПФ 1С.

Необходимо указывать данные с СФ, либо менять логику заполнения в подключаемом модуле.

**Comment by Olga5577** [comment]
спасибо
