### ISSUE TITLE
Свои константы и доп.свойства элементов справочников Диадок

### ISSUE THREAD

**Issue by Olga5577** [diadoc/diadoc1cpro-docs#61]
Добрый день.
Работаем с диадок про 4.5.29. в ерп .
Есть свои доработки в подкл.модуле.
Подскажите, пожалуйста, как правильно решить такие вопросы:
1. Для наших доработок нужны некие константы . Правильно ли будет создать эти константы в Диадок_дополнительныеСправочники, ОБщиеНастройки? Не затрутся ли они при обновлении Диадока на новые версии?
Или создать их просто в конфигурации ерп?
2. Также нужны доп.свойства элементов справочника Диадок_Документы. Можно ли их создавать, не боясь их потери при обновлении на новую версию диадока (технически это возможно, кнопка ДОбавить есть. )?

**Comment by Well3n** [comment]
Добрый день!
Да, можно использовать эти объекты и в последующих обновлениях , созданные константы, не затрутся.
Насчет доп.свойств элементов справочника Диадок_Документы, ответ тот же. Можете использовать и добавлять новые элементы в справочник.

**Comment by Olga5577** [comment]
Спасибо
