### ISSUE TITLE
Кнопка "Синхронизировать с сервером"

### ISSUE THREAD

**Issue by milanse** [diadoc/diadoc1cpro-docs#67]
При нажатии на кнопку начинает закачиваться весь справочник контрагентов с портала в систему. 

1. Спорным является сам вопрос хранения всего вашего справочника у меня в базе, а так же на сколько корректно он синхронизируется (у меня, например есть дубли)

1. На долго зависает процесс синхронизации с сервером, выводите хотя-бы предупреждение, что будет синхронизирован справочник, это займет продолжительное время. 

![image](https://user-images.githubusercontent.com/15941393/139846470-75cc3deb-65c0-47ed-8b2b-725cf1d2262c.png)

**Comment by Well3n** [comment]
Добрый день! 
Подскажите, есть ли возможность связаться с нашей технической поддержкой для сбора дополнительной информации для решения этого вопроса? 
Нам понадобиться:
-файл замера производительности;
-версия модуля с полной технической информацией о нем;
-версия конфигурации;
С нашей технической поддержкой можно связаться по любому указанному контакту на нашем сайте: https://www.diadoc.ru/support
