### ISSUE TITLE
Как включить отладку для модуля Диадок ПРО 5.52.01

### ISSUE THREAD

**Issue by ashkrobov** [diadoc/diadoc1cpro-docs#69]
Коллеги, добрый день! Поделитесь пожалуйста секретной информацией!? Как включить отладку для модуля Диадок ПРО 5.52.01

**Comment by volodkindv** [comment]
Добрый день!
5.52 - это версия модуля Стандарт (управляемые формы).
Отладка включается в настройках, как на скриншоте:
![image](https://user-images.githubusercontent.com/12305552/142566396-78df3279-a3ef-41e0-8d59-5fdd53e55590.png)
