### ISSUE TITLE
Ошибка при попытке добавить StructedAdditionalInfos.

### ISSUE THREAD

**Issue by Iron87Wolf** [diadoc/diadoc1cpro-docs#72]
Добрый день.
Возникла проблема. При попытке ДополнитьМассивKeyValue(Content.AdditionalInfoId.StructedAdditionalInfos, "Key", "Value"); в событии "ПодготовитьЭлектронныйДокумент" выдает ошибку :
`
{ВнешняяОбработка.ВнешняяОбработка1.МодульОбъекта(47)}: Ошибка при вызове метода контекста (Добавить)
		Массив.Добавить(НовыйЭлемент);
по причине:
Несоответствие типов XDTO:
Тип '{http://diadoc.kontur.ru/dll_types}AdditionalInfoItem' не найден
Значение не может быть установлено свойству, имеющему объектный тип
`
Подскажите пожалуйста с чем связана проблема ?
Версия обработки 4.8.2.1387

**Comment by PNK1C** [comment]
@Iron87Wolf  Добрый день, подскажите, пожалуйста, а как вы решили данную ошибку? Я что-то пока не смог найти решение, чтобы добавить структуру в XDTO

**Comment by Iron87Wolf** [comment]
> @Iron87Wolf Добрый день, подскажите, пожалуйста, а как вы решили данную ошибку? Я что-то пока не смог найти решение, чтобы добавить структуру в XDTO

Вот кусок кода из подключаемого модуля. Я не программист, так что над кодом не смеяться ))

`// Позволяет дополнить/изменить контент электронного документа
// перед его отправкой.
//
// Параметры
//  Параметры - Структура - Содержит коллекцию, переданных параметров:
//    * ТипКонтента         - Строка - идентификатор типа контента (см. ТипыКонтента());
//    * Content             - Структура - Протоконтент исходящего документа;
//    * ДокументСсылка     - ЛюбаяСсылка - Ссылка на документ информационной базы, по которому собирается протоконтент;
//    * DocumentType     - Строка - (Устарел) Позволяет определить тип протоструктуры.
//                                  Параметр сохранен для обратной совместимости с ПМ версии 1.1 или ниже.
//                                  Рекомендуется вместо него ориентироваться на ТипКонтента.
//
Функция ОбработатьСобытиеПодготовитьЭлектронныйДокумент(Параметры)
Перем номер_заказа ;
	Если ТипЗнч(Параметры) = Тип("Структура") И Параметры.Свойство("Результат_ИМ") Тогда

если (Найти(параметры.результат.Документ1С.Контрагент, "ПАО ""Детский мир"" (маркетплейс)")) и 
(Найти(параметры.результат.Документ1С.ссылка.ДоговорКонтрагента, "Маркетинговые услуги по Агентскому")) и 
(параметры.ВидДокументаРазвернутый.ТипКонтента="Utd820SellerContent") тогда

	Если ВвестиЧисло(номер_заказа, "Введите номер заказа на маркетинговые услуги по " + параметры.результат.Документ1С , 20, 0) Тогда
    Content= Параметры.Результат.Content;
    ТипКонтента= Параметры.Результат.ТипКонтента;
		НовЭлемент = НовыйЭлементСпискаXDTO(Content.AdditionalInfoId.StructedAdditionalInfos);
		Заполнить_AdditionalInfoItem(НовЭлемент, "Назначение", "Услуги маркетплейс");
		НовЭлемент = НовыйЭлементСпискаXDTO(Content.AdditionalInfoId.StructedAdditionalInfos);
		Заполнить_AdditionalInfoItem(НовЭлемент, "номер_заказа", номер_заказа);
		КонецЕсли;	
конецесли
	КонецЕсли;

КонецФункции
`

**Comment by PNK1C** [comment]
> > @Iron87Wolf Добрый день, подскажите, пожалуйста, а как вы решили данную ошибку? Я что-то пока не смог найти решение, чтобы добавить структуру в XDTO
> 
> Вот кусок кода из подключаемого модуля. Я не программист, так что над кодом не смеяться ))
> 
> `// Позволяет дополнить/изменить контент электронного документа // перед его отправкой. // // Параметры // Параметры - Структура - Содержит коллекцию, переданных параметров: // * ТипКонтента - Строка - идентификатор типа контента (см. ТипыКонтента()); // * Content - Структура - Протоконтент исходящего документа; // * ДокументСсылка - ЛюбаяСсылка - Ссылка на документ информационной базы, по которому собирается протоконтент; // * DocumentType - Строка - (Устарел) Позволяет определить тип протоструктуры. // Параметр сохранен для обратной совместимости с ПМ версии 1.1 или ниже. // Рекомендуется вместо него ориентироваться на ТипКонтента. // Функция ОбработатьСобытиеПодготовитьЭлектронныйДокумент(Параметры) Перем номер_заказа ; Если ТипЗнч(Параметры) = Тип("Структура") И Параметры.Свойство("Результат_ИМ") Тогда
> 
> если (Найти(параметры.результат.Документ1С.Контрагент, "ПАО ""Детский мир"" (маркетплейс)")) и (Найти(параметры.результат.Документ1С.ссылка.ДоговорКонтрагента, "Маркетинговые услуги по Агентскому")) и (параметры.ВидДокументаРазвернутый.ТипКонтента="Utd820SellerContent") тогда
> 
> ```
> Если ВвестиЧисло(номер_заказа, "Введите номер заказа на маркетинговые услуги по " + параметры.результат.Документ1С , 20, 0) Тогда
> Content= Параметры.Результат.Content;
> ТипКонтента= Параметры.Результат.ТипКонтента;
> 	НовЭлемент = НовыйЭлементСпискаXDTO(Content.AdditionalInfoId.StructedAdditionalInfos);
> 	Заполнить_AdditionalInfoItem(НовЭлемент, "Назначение", "Услуги маркетплейс");
> 	НовЭлемент = НовыйЭлементСпискаXDTO(Content.AdditionalInfoId.StructedAdditionalInfos);
> 	Заполнить_AdditionalInfoItem(НовЭлемент, "номер_заказа", номер_заказа);
> 	КонецЕсли;	
> ```
> 
> конецесли КонецЕсли;
> 
> КонецФункции `

Спасибо вам большое) Разобрался)
