### ISSUE TITLE
КонтурЭДО 4.8.2.1387: Авторизация по сертификату

### ISSUE THREAD

**Issue by GulshatF** [diadoc/diadoc1cpro-docs#74]
Здравствуйте, хотим использовать модуль КонтурЭДО 4.8.2.1387 в 1С УТ11. 
Сделали подключаемый модуль , добавили функцию:

 Функция ВыполнитьРегламентныеДействия(Параметры)
   ОсновнойМодуль.ЭДО_АвторизоватьсяПодСертификатомНаСервере1С();
   КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();
   ...

, но при запуске регл.задания пишет "не удалось авторизоваться по логину", 

как указать, что надо авторизоваться по сертификату?

**Comment by GulshatF** [comment]
Такая запись в журнал регистрации пишется:

Выполнение операции: Авторизация по логину.
Password: Password not found
{ВнешняяОбработка.КонтурМетодыAPI.МодульОбъекта(174)}:		ВызватьИсключение ТекстОшибки;
{ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(6620)}:	Результат = Модуль_МетодыAPI.DD_API_Authenticate(ПараметрыСервиса, Сертификат, Логин, Пароль);
{ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(14696)}:	Результат = АПИ_Authenticate(ПараметрыСервиса, Сертификат, Логин, Пароль);
{ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(14762)}:		Токен = Токен_ПолучитьИзДиадока(, Логин, Пароль);
{ВнешняяОбработка.ДиадокВызовыПМ.МодульОбъекта(2897)}:	Результат = Ядро.**Авторизация_ПоПаролю**(Логин, Пароль);
{ВнешняяОбработка.ДД_подключаемыйМодуль.МодульОбъекта(1393)}:	ОсновнойМодуль.**ЭДО_АвторизоватьсяПодЛогином**(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль);
{ВнешняяОбработка.ДД_подключаемыйМодуль.МодульОбъекта(154)}:		Возврат ВыполнитьРегламентныеДействия(Параметры);
{ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(8777)}:					Результат_ИМ = ИМ.ОбработатьСобытие(ИмяСобытия, Параметры);
{Обработка.КонтурЭДО.МодульОбъекта(4278)}:	Модуль_Ядро().ПодключаемыйМодуль_ОбработатьСобытие("ВыполнитьРегламентныеДействия", ПараметрыВыполненияКоманды);
{Обработка.КонтурЭДО.МодульОбъекта(4269)}:		ВыполнитьРегламентныеДействия(ПараметрыВыполненияКоманды);
{Обработка.ОбменСR2.Форма.Форма.Форма(117)}:	ОбработкаДиадокПро.ВыполнитьКоманду("ЭДО_ВыполнитьРегламентныеДействия", "");
Логин: ...

**Comment by volodkindv** [comment]
Добрый день.
Текст ошибки говорит о том, что не задан пароль.
Если вам нужна авторизация под сертификатом, то надо убрать из кода подключаемого модуля авторизацию под логином:
```
ОсновнойМодуль.ЭДО_АвторизоватьсяПодЛогином(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль);
```

**Comment by GulshatF** [comment]
в том-то и дело, что в подключаемом модуле нет ЭДО_АвторизоватьсяПодЛогином

**Comment by GulshatF** [comment]
Функция ВыполнитьРегламентныеДействия(Параметры)
	ОсновнойМодуль.**ЭДО_АвторизоватьсяПодСертификатомНаСервере1С**();  
	КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();
	ПараметрыОбновленияСписка = Новый Структура;
	ПараметрыОбновленияСписка.Вставить("НачалоПериода", '20210907');
	ПараметрыОбновленияСписка.Вставить("КонецПериода", КонецДня('20210907'));
	//ПараметрыОбновленияСписка.Вставить("ОтборПоКонтрагенту", Справочники.Контрагенты.НайтиПоНаименованию("АО ""..."""));
	//ПараметрыОбновленияСписка.Вставить("ВключитьОтборПоКонтрагенту", Истина);
	ПараметрыОбновленияСписка.Вставить("ВключитьОтборПоОрганизации", Ложь);
	ПараметрыОбновленияСписка.Вставить("Режим", "ПолученныеДокументы");
	ПараметрыОбновленияСписка.Вставить("РежимОтбораПоПериоду", "ПоДатеОтправкиИлиПолучения");
	ПараметрыОбновленияСписка.Вставить("ВключитьОтборПоСтатусу", ложь);
	ПараметрыОбновленияСписка.Вставить("МассивВыбранныхВидов", Новый Массив);
	ПараметрыОбновленияСписка.Вставить("ПоказыватьЗавершенные",ложь);
	ОсновнойМодуль.ЭДО_Модуль_ОбновитьСписокДокументов(ПараметрыОбновленияСписка);
	Для Каждого СтрокаТЧ Из ОсновнойМодуль.СписокДокументов Цикл
		//ОсновнойМодуль.ЭДО_ПодготовитьИОт
	КонецЦикла;
КонецФункции

**Comment by volodkindv** [comment]
Попробуйте добавить в конце
```
Возврат Истина;
```

**Comment by GulshatF** [comment]
Удалось авторизоваться только по логину-паролю. 
Получить список документов удалось получить, добавив после авторизации строку:
                
ОсновнойМодуль.ЭДО_ЗаполнитьКонтекстСеансаДляСлужебнойУчетнойЗаписи();

После добавления строки:
                 Возврат Истина;
регламентное задание стало выполняться 1 раз (а не 2, как до этого)

**Comment by volodkindv** [comment]
@GulshatF в итоге вопрос решен или открыт?

**Comment by GulshatF** [comment]
Авторизуемся по логину-паролю. На этом вопрос закрыли.
