### ISSUE TITLE
Ошибка HTTP запроса Код ошибки: 400  Пакет: СФ + ТОРГ12/Акт по документу Счет-фактура выданный 0465910112220101/77 от 20.12.2021 23:59:59 Не удалось отправить пакет документов: Ошибка HTTP запроса Код ошибки: 400 MessageToPost.DocumentAttachments[2]: Имя файла не должно содержать символы < > : “ / \ | ? * или заканчиваться точкой, пробелом. 

### ISSUE THREAD

**Issue by Armageddon2512** [diadoc/diadoc1cpro-docs#76]
**Добрый день. Прошло пол года и вы смогли закрыть заявку 31659510
https://github.com/diadoc/diadoc1cpro-docs/issues/44

Прислали новый модуль, я посмотрел на тесте, допилил новый подключаемый модуль, вроде всё работает.
Пытаюсь отправить пакет документов у меня ошибка: **

_Очистить и закрыть
HTTP запрос в сервис diadoc-api.kontur.ru.

Ошибка HTTP запроса Код ошибки: 400 MessageToPost.DocumentAttachments[2]: Имя файла не должно содержать символы < > : “ / \ | ? * или заканчиваться точкой, пробелом. Исправьте и загрузите документ еще раз. Метод: POST Адрес метода: https:// diadoc-api.kontur.ru/V3/PostMessage
Отправка пакета документов.

Пакет: СФ + ТОРГ12/Акт по документу Счет-фактура выданный 0465910112220101/77 от 20.12.2021 23:59:59 Не удалось отправить пакет документов: Ошибка HTTP запроса Код ошибки: 400 MessageToPost.DocumentAttachments[2]: Имя файла не должно содержать символы < > : “ / \ | ? * или заканчиваться точкой, пробелом. Исправьте и загрузите документ еще раз. {ВнешняяОбработка.КонтурВнешниеСервисы.МодульОбъекта(155)}:	ВызватьИсключение ТекстОшибки; {ВнешняяОбработка.КонтурМетодыAPI.МодульОбъекта(2860)}:	Результат = Модуль.ВыполнитьHTTPЗапрос(ПараметрыСервиса, ПараметрыЗапроса); {ВнешняяОбработка.КонтурМетодыAPI.МодульОбъекта(1141)}:	Ответ = ВнешниеСервисы_ВыполнитьHTTPЗапрос(ПараметрыСервиса, ПараметрыЗапроса); {ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(6811)}:	Результат = Модуль_МетодыAPI.DD_API_PostMessage(ПараметрыСервиса, MessageToPost, OperationId); {ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(17768)}:	РезультатОтправки = АПИ_PostMessage(ПараметрыСервиса, MessageToPost, OperationId); {ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(17651)}: РезультатОтправки = Пакеты_ОтправитьPostMessage(Пакет, MessageToPost, OperationId); {ВнешняяОбработка.ДиадокЯдро.МодульОбъекта(17545)}:	ОтправкаВыполнена = Пакеты_Отправить(Пакет); {(1)}:Модуль_Ядро().Пакеты_ОтправитьИСохранить(Параметр0) {ВнешняяОбработка.КонтурЭДО.Форма.Модуль_Платформа.Форма(66)}:	Возврат Вычислить(ИмяМетода + "(" + СтрокаПараметров + ")");_

Наша техническая информация:

Версия модуля: 4.8.24.1387
Версия плагина: 1.4.1.190
Модуль типовой: нет
Расположение модуля: НаДиске
Имя модуля: C:\Users\a.kolesnikov\Desktop\ДИАДОК\4_8_24\Diadoc 4_8_24.epf
Конфигурация: 1С:ERP Управление предприятием 2 (2.4.13.278)
Модуль интеграции: ПМ_УТ_11

Подключаемый модуль на диске: \\s-sem-1csrv01\D$\Диадок\ПМ_WestCall.epf
Тип платформы: Windows x86-64
Версия платформы: 8.3.17.1496
Версия ОС: Microsoft Windows 8.1 version 6.3  (Build 9600)
Вид клиента: Сервер
Строка соединения: Srvr="s-sem-1csrv01:2541";Ref="rab_westcall_complex-automatization";
Каталог временных файлов: C:\Users\1C83USR\AppData\Local\Temp\

Настройки модуля:
Режим прокси: использовать системные настройки
Загружать исходящие документы: Нет
Загружать входящие документы: Да
Загружать документы только по сопоставленным контрагентам: Нет
Разрешить фоновые операции: Да
Сценарий сохранения документов: весь документооборот
Хранить документы на диске: Нет
Загружать документооборот целиком: Нет
Использовать типовые объекты 1С: Нет
Режим логирования: Нет
Режим отладки: Нет
Отключить контроль дублирования: Нет
Показать количество документов в пакете в разделе "Для отправки": Нет
Отключить анализ для входящих документов: Нет
Указывать отсутствие основания УПД: Нет
Отправлять непроведенные документы: Нет
Записывать комментарий при отправке: Нет
Записывать комментарий при создании/сопоставлении: Нет
Использовать сервис "Контур.Маркировка": Нет

Настройки Стандарта:
Подключаемый модуль на диске: \\fat\Projects\Public\ЭДО\Диадок_КА\ВестКоллКА_подключаемый_модуль - копия.epf
Режим совместимости форматов 155 и 820: Нет

BoxId: 9acc98d0bd1d4ec9b883a6d082beb2a1@diadoc.ru
Отпечаток сертификата: 3e39fb7bef8231a19e77eb4991f4394aa294fd1a
Login для обмена: не заполнен
UserId: 580e2154-c13c-4d4c-9944-a6ba74601f45

Подключенные библиотеки:
 - Ядро вер. 0.1.4.85 (Макет)
 - ГенерацияXML вер. 4.9.2.123 (Макет)
 - ОсновнойМодуль вер. 4.8.24 (Макет)
 - ПарсерJSON вер. 1.0.0.2 (Макет)
 - АсинхронныеМетоды вер. 0.1.0.2 (Макет)
 - ВнешниеСервисы вер. 0.4.0.3 (Макет)
 - МетодыAPI вер. 0.1.0.10 (Макет)
 - ВызовыПМ вер. 0.1.0.15 (Макет)
 - ПечатныеФормы вер. 1.5.2.93 (Макет)
 - ПМ вер. 4 (Макет)
 - ХранениеДанных вер. 0.1.1.33 (Макет)
 - Плагин вер. 1.1.15 (Макет)
 - ЭмуляторТабДокумента вер. 0.1.0.2 (Макет)
 - УведомленияПользователей вер. 1.0.2.1 (Макет)
 - ИМ вер. 4 (Макет)
Пропустить обновление библиотек: Нет

**Полез в законодательство, может мы не правы, а нет можем использовать / в номерах счёт фактуре.
https://glavkniga.ru/elver/2012/10/734-vozmozhna_obosoblennaja_numeratsija_avansovikh_schetov_faktur.html**

ТАК ЧТО АЛЛАРМ, С 1 января мы должны уже новую обработку использовать!!!!

ИНН 7702388235, КПП 771901001
Номер вашего обращения – 43622998.

**Comment by ButurlakinSemyon** [comment]
@Armageddon2512 , добрый день.

Можете приложить:
1. ПМ
2. Файл документа, который вызывает ошибку.

**Comment by Armageddon2512** [comment]
[4_8_2.zip](https://github.com/diadoc/diadoc1cpro-docs/files/7760647/4_8_2.zip)
[ПМ_WestCall.zip](https://github.com/diadoc/diadoc1cpro-docs/files/7760660/_WestCall.zip)

**Comment by Armageddon2512** [comment]
Так как ваша поддержка обвиняла, что у наспробелы на конце номера в документах, то я во всех модулях добавил СОКРЛП() и ошибка осталась. Прикрепил ПМ модуль
[ПМ_WestCall.zip](https://github.com/diadoc/diadoc1cpro-docs/files/7761446/_WestCall.zip)

**Comment by ButurlakinSemyon** [comment]
@Armageddon2512, если судить по тексту ошибки, то в отправляемом пакете как минимум 3 документа, а ошибка возвращается только на один. 

В ПМ есть логика добавления в пакет еще документа "ЗаказКлиента" с типом ProformaInvoice. Подозреваю, что в получаемом имени файла и присутствуют недопустимые символы. Надо эти символы исключить в ПМ.

**Comment by Armageddon2512** [comment]
Доброе утро. Не ужели вы со своей поддержкой не общаетесь?? Я им отправлял два скриншота, когда есть счёт и когда его нету!!! Дублирую сюда.....
![Снимок2](https://user-images.githubusercontent.com/52042400/147193052-1fe95831-c3d1-4645-9ca9-2f1f508a28c2.PNG)
![Снимок](https://user-images.githubusercontent.com/52042400/147193057-d39a4874-146b-446b-a246-72ca30b8a322.PNG)

**Comment by Armageddon2512** [comment]
> @Armageddon2512, если судить по тексту ошибки, то в отправляемом пакете как минимум 3 документа, а ошибка возвращается только на один.
> 
> В ПМ есть логика добавления в пакет еще документа "ЗаказКлиента" с типом ProformaInvoice. Подозреваю, что в получаемом имени файла и присутствуют недопустимые символы. Надо эти символы исключить в ПМ.

Ответил выше

**Comment by milanse** [comment]
Присмотритесь к своему скрину и сообщению об ошибке, у вас же запрещённые символы в имени файла \

**Comment by Armageddon2512** [comment]
> Присмотритесь к своему скрину и сообщению об ошибке, у вас же запрещённые символы в имени файла \

Одно дело если бы я это не видел.... Так я это вижу.... Дело в том что 3.2.63 позволяло отправлять с таким именем файлов, а новая версия 4.8.24 не даёт. Подозреваю что изменились REST запросы, но с точки зрения законодательства мы имеем права отправлять и присваивать такие номера счёт-фактур.... Так что проблема на вашей стороне. Или я не прав? Поправьте меня.

**Comment by milanse** [comment]
@Armageddon2512 ,  как вы видите процесс сохранения файла с таким именем у клиента ? Как сами его сохраняете ?

**Comment by Armageddon2512** [comment]
> @Armageddon2512 , как вы видите процесс сохранения файла с таким именем у клиента ? Как сами его сохраняете ?

Не понял вопроса.

**Comment by Armageddon2512** [comment]
Добрый день. Беспокою по обращению 43633087, очень мало времени остаётся. Какие результаты есть?

**Comment by ButurlakinSemyon** [comment]
@Armageddon2512, добрый день! Судя по тех информации, у вас есть есть ПМ стандарта:
```
Настройки Стандарта:
Подключаемый модуль на диске: \ fat \ Projects \ Public \ ЭДО \ Диадок_КА \ ВестКоллКА_подключаемый_модуль - копия.epf
Режим совместимости форматов 155 и 820: Нет
```
Можете его присалать?

**Comment by Armageddon2512** [comment]
Странный модуль, для чего он?
[ВестКоллКА_подключаемый_модуль - копия.zip](https://github.com/diadoc/diadoc1cpro-docs/files/7783045/_._.-.zip)

**Comment by ButurlakinSemyon** [comment]
Это ПМ от стандарта. Видимо до универсального модуля, вы использовали модуль стандарт УФ, для которого использовался ПМ. При переходе со стандарта на универсальный, ПМ стандарта автоматом подхватывается.

**Comment by Armageddon2512** [comment]
и чем это нам поможет? его не трогали с начала 2020 года

**Comment by ButurlakinSemyon** [comment]
@Armageddon2512, в ПМ для универсального модуля (ПМ_WestCall) необходимо внести правки:

В процедуре "ПодготовитьЭлектронныйДокумент"
Заменить запрещённые символы в имени файла.
В частности в ветках ID_Акт, ID_ЗаказКлиента, ID_Договор, ID_ДопДокументы

Там есть такая конструкция
Результат.Метаданные.FileName
Результат.ИмяФайла

Эти 2 атрибута не должны содержать запрещённых символов.

> с точки зрения законодательства мы имеем права отправлять и присваивать такие номера счёт-фактур - Да, такие номера использовать можно. Но в данном случае проблема связана с именем файла, а не номером документа.

**Comment by Armageddon2512** [comment]
> Доброе утро @ButurlakinSemyon. Не ужели вы со своей поддержкой не общаетесь?? Я им отправлял два скриншота, когда есть счёт и когда его нету!!! Дублирую сюда..... ![Снимок2](https://user-images.githubusercontent.com/52042400/147193052-1fe95831-c3d1-4645-9ca9-2f1f508a28c2.PNG) ![Снимок]

Тогда почему при отправке счёт фактуры и акта ошибка повторяется? Скриншот приложен выше!

**Comment by ButurlakinSemyon** [comment]
У вас в ветке ID_Акт формируется имя для акта.

**Comment by Armageddon2512** [comment]
> Да, такие номера использовать можно. Но в данном случае проблема связана с именем файла, а не номером документа.

А разве это мы должны править?

**Comment by ButurlakinSemyon** [comment]
Если ПМ был реализован вами самостоятельно, то правки необходимо вносить самим.

Проверить сформированное имя файла можно проверить таким способом:
1. На форме пакета нажать правой кнопкой мыши на документ и выбрать пункт - "Показать информацию"
![image](https://user-images.githubusercontent.com/74642650/147637113-ab111f29-6528-419e-8a46-c7c6162f41cc.png)
2. В открывшемся окне "Информации о пакете" найти поле "ИмяФайла"
![image](https://user-images.githubusercontent.com/74642650/147637161-bbe8f3b9-3ee8-462e-93d7-cbd195cb2056.png)


По поводу версии 3.2 к сожалению подсказать не могу. Возможно, на стороне Апи была добавлена валидация.

**Comment by Armageddon2512** [comment]
Могу прислать 3.2.
[Uploading Diadoc_3_2_63_WestCall_2021_09_15.zip…]()

читаю обращение не закрытым и просто отписываетесь от нас, хотя ошибка в самом модуле
Потому что это не мы поменяли АПИ, а ваши разработчики. 
Прошу выпустить новую версию обработки с исправление данной ошибки.

**Comment by Armageddon2512** [comment]
> Если ПМ был реализован вами самостоятельно, то правки необходимо вносить самим.
> 
> Проверить сформированное имя файла можно проверить таким способом:
> 
> 1. На форме пакета нажать правой кнопкой мыши на документ и выбрать пункт - "Показать информацию"
>    ![image](https://user-images.githubusercontent.com/74642650/147637113-ab111f29-6528-419e-8a46-c7c6162f41cc.png)
> 2. В открывшемся окне "Информации о пакете" найти поле "ИмяФайла"
>    ![image](https://user-images.githubusercontent.com/74642650/147637161-bbe8f3b9-3ee8-462e-93d7-cbd195cb2056.png)
> 
> По поводу версии 3.2 к сожалению подсказать не могу. Возможно, на стороне Апи была добавлена валидация.

Хочу напомнить, что ошибка остаётся и без подключаемого модуля. Так что обращение актуально

**Comment by ButurlakinSemyon** [comment]
Можете прислать скрин с именами файлов в случае, когда ПМ отключен.

**Comment by Armageddon2512** [comment]
![image](https://user-images.githubusercontent.com/52042400/147658998-8cf6534b-19a3-442d-bbdf-f26025fbf7ee.png)
![image](https://user-images.githubusercontent.com/52042400/147659034-a01464f2-255d-42d3-99ba-67c5c7fdcd85.png)

**Comment by ButurlakinSemyon** [comment]
Было проведено УД. Результат:
Формировался неформализованный документ с запрещенными символами в имени файла. Поправили процедуру формирования имени, ошибка устранена.
