### ISSUE TITLE
User with Id=[...] is blocked in organization with BoxId=[...]

### ISSUE THREAD

**Issue by GulshatF** [diadoc/diadoc1cpro-docs#79]
Здравствуйте, мы используем модуль КонтурЭДО 4.8.2.1387 в 1С УТ11.

В подключаемый модуль добавили функцию:

Функция ВыполнитьРегламентныеДействия(Параметры)
   // АВТОРИЗАЦИЯ ПО ЛОГИНУ И ПАРОЛЮ
   ОсновнойМодуль.ЭДО_АвторизоватьсяПодЛогином(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль);	
   КонтекстСеанса = ОсновнойМодуль.ЭДО_КонтекстСеансаКлиентСервер();
   ОсновнойМодуль.ЭДО_ЗаполнитьКонтекстСеансаДляСлужебнойУчетнойЗаписи();	
   ...

, но при выполнении регл.задания пишет ошибку: "Код ошибки: 403
User with Id=[9ee...bda] is blocked in organization with BoxId=[65b...85]
Метод: GET
Адрес метода: https:// diadoc-api.kontur.ru/GetMyPermissions

Пользователь действительно уволен и заблокирован в личном кабинете Диадок, но как передается ссылка на него, и как от этого избавиться? Подскажите, пожалуйста!
(если пользователя разблокировать, всё работает)

**Comment by GordanovaKseniya** [comment]
Добрый день!
Уточните, пожалуйста, сценарий: авторизация в модуле произведена под действующим пользователем?

**Comment by GulshatF** [comment]
Добрый день.
Насколько я понимаю, в регламентном задании авторизация должна проходить по логину и паролю:

Функция ВыполнитьРегламентныеДействия(Параметры)
// АВТОРИЗАЦИЯ ПО ЛОГИНУ И ПАРОЛЮ
ОсновнойМодуль.ЭДО_АвторизоватьсяПодЛогином(УчетнаяЗапись().Логин, УчетнаяЗапись().Пароль);
...

само регл. задание запускается от имени пользователя для регл. заданий

**Comment by AleksandrSurin** [comment]
Добрый день, @GulshatF!
Все верно, в приведенном вами коде авторизация выполняется под служебной учетной записью, которая указывается в настройках модуля. Проверьте, что там указано. Можно также выполнить проверку указанной учетной записью, нажав кнопку "Проверить авторизацию" в форме настроек. Отпишитесь, пожалуйста, по результату проверки

**Comment by GulshatF** [comment]
логин/пароль указан. Проверка возвращает "Авторизация пройдена успешно"

**Comment by AleksandrSurin** [comment]
Приложите ПМ, пожалуйста

**Comment by AleksandrSurin** [comment]
@GulshatF, приложите ПМ и тех. информацию, пожалуйста

**Comment by GulshatF** [comment]
тут: https://disk.yandex.ru/d/RgIVwHMrnhM8sQ

**Comment by AleksandrSurin** [comment]
@GulshatF, метод, указанный в ПМ, ЭДО_ЗаполнитьКонтекстСеансаДляСлужебнойУчетнойЗаписи() использует для авторизации логин и пароль, которые указаны в настройках модуля (служебная учетная запись).
Вам необходимо проверить, что пользователь, который указан в настройках в качестве служебного имеет доступ ко всем ящикам (организациям). У него нет заблокированных организаций. Если есть, попробуйте указать другого пользователя.

**Comment by AleksandrSurin** [comment]
@GulshatF, добрый день! Ваш вопрос еще актуален?

**Comment by JulyMalysh** [comment]
Добрый день. 
Подскажите, чем может быть вызвана ошибка?

Ошибка Kontur.1C.Plugin.Host
type : PLUGIN
message : PLUGIN[0x00000001]test.wait invalid command structure: Waiting time must not exceed 30 mintues.
code : 1
context : test.wait
details : Waiting time must not exceed 30 mintues.

**Comment by JulyMalysh** [comment]
Добрый день. 
При загрузке файлов по api из Диадок с ЭП. Названия файлов и ЭП приходят без кавычек, буква "й" меняется на "и" или на " " (пробел). Какие еще могут быть изменения в наименовании файлов?

**Comment by GilimkhanovDenis** [comment]
@JulyMalysh Добрый день

Вы описываете ошибки никак не связанные с первоначальным обращением, которое было решено почти 2 года назад. Рекомендую для каждой из ситуаций создать отдельное обращение с примерами - для каких документов / в каком сценарии, на какой версии модуля
