### ISSUE TITLE
Как отладить "Подключаемый модуль" в составе конфигурации?

### ISSUE THREAD

**Issue by IntellXeon** [diadoc/diadoc1cpro-docs#93]
Как отладить "Подключаемый модуль" в составе конфигурации? Точки останова стоят. отладка на сервере подключена, но модуль не как не реагирует не на какие манипуляции! Что делаем не так?
1С УТ 11.4.11.63

![image](https://user-images.githubusercontent.com/108328954/176132847-d0d1e257-4af0-4b4c-af78-06fa396c373c.png)

**Comment by kulakovskaya** [comment]
Здравствуйте! Приложите, пожалуйста, техническую информацию из модуля.
