### ISSUE TITLE
Коды маркировки в УПД

### ISSUE THREAD

**Issue by Scherbakov-YA** [diadoc/diadoc1cpro-docs#96]
Подскажите, пожалуйста какую функцию подключаемого модуля диадока нужно дорабатывать для заполнения кодов маркировки при отправке УПД? Есть ли пример кода?

**Comment by ButurlakinSemyon** [comment]
@Scherbakov-YA добрый день!
Для заполнения маркировки необходимо доработать функцию "ПодготовитьЭлектронныйДокумент", например:
```
Функция ПодготовитьЭлектронныйДокумент(Параметры)
	// Имя шаблона: Произвольное изменение контента УПД
	Если ТипЗнч(Параметры) = Тип("Структура") И Параметры.Свойство("Результат_ИМ") Тогда
		Content		= Параметры.Результат.Content;
		Документ1С 	= Параметры.Результат.Документ1С;
		ВидДокументаРазвернутый = Параметры.ВидДокументаРазвернутый;
		ТипКонтента_XDTO = ВидДокументаРазвернутый.ТипКонтента;
		Если ВРЕГ(ТипКонтента_XDTO) = ВРЕГ("Utd820SellerContent") Тогда
			УПД_ИзменитьКонтент(Content, Документ1С);
		КонецЕсли;
		Возврат Истина;
	КонецЕсли;
КонецФункции
```
В процедуре УПД_ИзменитьКонтент(Content, Документ1С) необходимо:
```
Процедура УПД_ИзменитьКонтент(Content, Документ1С)
    Для Каждого Строка из Content.Table.Items Цикл
        НовыйЭлемент = УПД_Товар_ДобавитьНомСредИдентТов(Строка);
        НомСредИдентТов_ЗаполнитьИдентТрансУпак(НовыйЭлемент, ????);
    КонецЦикла;
КонецПроцедуры

Функция УПД_Товар_ДобавитьНомСредИдентТов(Item)
    ItemIdentificationNumber = ОсновнойМодуль.НовыйЭлементСпискаXDTO(Item.ItemIdentificationNumbers);
    Возврат ItemIdentificationNumber;
КонецФункции

Процедура НомСредИдентТов_ЗаполнитьИдентТрансУпак(ItemIdentificationNumber, ИдентТрансУпак)
    Если ItemIdentificationNumber = Неопределено Тогда
        Возврат;
    КонецЕсли;
    ItemIdentificationNumber.TransPackageId = ИдентТрансУпак;
КонецПроцедуры
```

**Comment by Scherbakov-YA** [comment]
В строке с вопросами как получить номенклатуру обрабатываемой строки и количество?

**Comment by ButurlakinSemyon** [comment]
@Scherbakov-YA В контенте есть коллекция Items, для каждой строки пробегаемся в цикле
```
Процедура УПД_ИзменитьКонтент(Content, Документ1С)

  Для Каждого Строка Из Content.Table.Items Цикл
    
    НовыйЭлемент = УПД_Товар_ДобавитьНомСредИдентТов(Строка);
    
    //ВидУпаковки = <это реквизит элемента справочника Штрихкоды упаковок>
    
    //ЗначениеКодаМаркировки = <сам штрих код - строка>
    
    Если ВидУпаковки = Перечисления.ВидыУпаковокИС.Групповая Тогда
      НовыйЭлемент.PackageIds.Добавить(ЗначениеКодаМаркировки);
      
    ИначеЕсли ВидУпаковки = Перечисления.ВидыУпаковокИС.Логистическая Тогда
      НовыйЭлемент.TransPackageId = ЗначениеКодаМаркировки;
      
    Иначе
      НовыйЭлемент.Units.Добавить(ЗначениеКодаМаркировки);
      
    КонецЕсли;
    
  КонецЦикла;  
  
КонецПроцедуры
```
Скрин коллекции Items:
![image](https://user-images.githubusercontent.com/74642650/182533398-813b3756-c0cb-495c-a4c0-be23545119a6.png)

**Comment by Scherbakov-YA** [comment]
я немного про другое. Для того чтобы получить код маркировки для ОСУ нужен штрихкод. Чтобы получить штрихкод нудна ссылка на номенклатуру 1с. Отсюда вопрос. Как получить ссылку на номенклатуру? Где она хранится?

**Comment by ButurlakinSemyon** [comment]
@Scherbakov-YA  
Коллекция Items = Товары документа. В ней нет ссылок, т.к. это уже готовая для формирования файла XML коллекция. Из нее можно взять наименование номенклатуры или код номенклатуры или артикул, поискать в базе 1с и получить ссылку.
Но это справедливо только в том случае, если вы дополняете контент собранный коробкой. 
Вы хотите дополнить контент документа или собрать его вручную с нуля?

**Comment by Scherbakov-YA** [comment]
Код маркировки в базе у меня не хранится. Мне нужно его сгенерировать и записать в нужный реквизит

**Comment by ButurlakinSemyon** [comment]
@Scherbakov-YA давайте начнем с начала :)
Вы используете типовую логику модуля в части формирования электронного УПД. Но так как в 1С маркировка не хранится, в XML УПД коды маркировки отсутствуют. Поэтому в подключаемом модуле требуется дополнить УПД кодами маркировки.
Все верно?

**Comment by Scherbakov-YA** [comment]
точно.
И сейчас нужна работа с кодом объемно сортового учета. Т.е. на каждую строку код будет только один.
Поэтому нужно указывать какой-то тип именно под этот код. Т.е. не код палеты, не код коробки, а код ОСУ штучки.

**Comment by Scherbakov-YA** [comment]
<НомСредИдентТов>
            <НомУпак>0204607128366054375</НомУпак>
          </НомСредИдентТов>
        </ДопСведТов>

вот пример упд с кодом маркировки оформленный через EDI.
Как тоже самое сделать через модуль ЭДО?

**Comment by Scherbakov-YA** [comment]
И еще вопрос. Мы используем 1с УПП 1.3.
Есть ли там какие-нибудь типовые реквизиты, где хранятся коды маркировки, которые использует модуль диадока по умолчанию?
Может быть проще сформировать код маркировки куда-нибудь записать в базу 1с, а ваш модуль сам возьмет его?

Или же если для номенклатуры заведен штрихкод, то модуль итак сам формирует код ОСУ, а я зря поднимаю панику?
Проясните, пожалуйста.

**Comment by ButurlakinSemyon** [comment]
По УПП 1.3 подсказать, к сожалению, не могу. Модуль пока не поддерживает работу с ОСУ из коробки, на стороне 1С это также еще реализовано. 

ОСУ необходимо заполнять в PackageIds (НомУпак) , в коллекции [ItemIdentificationNumber](https://developer.kontur.ru/Docs/Diadoc_UM/objects/Item820.html#:~:text=ItemIdentificationNumbers).

```
Процедура НомСредИдентТов_ДобавитьНомУпак(ItemIdentificationNumber, НомУпак)
	
	Если ItemIdentificationNumber = Неопределено Тогда
		Возврат;
	КонецЕсли;
	
	ItemIdentificationNumber.PackageIds.Добавить(НомУпак);

КонецПроцедуры
```

Пример результата в XML:
![image](https://user-images.githubusercontent.com/74642650/182552473-fc9287f7-491c-43bd-81e0-de5511072bf6.png)

**Comment by Scherbakov-YA** [comment]
Сгенерировал подключаемый модуль. Процедуры НомСредИдентТов_ДобавитьНомУпак в нем нет.

Есть только:
ОбработатьСобытие
ПодготовитьЭлектронныйДокумент
СведенияОВнешнейОбработке
ПолучитьТаблицуКоманд
ДобавитьКоманду
ВыполнитьКоманду
ВыполнитьРегламентныеДействияПМ
ЭДО_ВерсияAPIПодключаемогоМодуля

**Comment by Scherbakov-YA** [comment]
> @Scherbakov-YA добрый день! Для заполнения маркировки необходимо доработать функцию "ПодготовитьЭлектронныйДокумент", например:
> 
> ```
> Функция ПодготовитьЭлектронныйДокумент(Параметры)
> 	// Имя шаблона: Произвольное изменение контента УПД
> 	Если ТипЗнч(Параметры) = Тип("Структура") И Параметры.Свойство("Результат_ИМ") Тогда
> 		Content		= Параметры.Результат.Content;
> 		Документ1С 	= Параметры.Результат.Документ1С;
> 		ВидДокументаРазвернутый = Параметры.ВидДокументаРазвернутый;
> 		ТипКонтента_XDTO = ВидДокументаРазвернутый.ТипКонтента;
> 		Если ВРЕГ(ТипКонтента_XDTO) = ВРЕГ("Utd820SellerContent") Тогда
> 			УПД_ИзменитьКонтент(Content, Документ1С);
> 		КонецЕсли;
> 		Возврат Истина;
> 	КонецЕсли;
> КонецФункции
> ```
> 
> В процедуре УПД_ИзменитьКонтент(Content, Документ1С) необходимо:
> 
> ```
> Процедура УПД_ИзменитьКонтент(Content, Документ1С)
>     Для Каждого Строка из Content.Table.Items Цикл
>         НовыйЭлемент = УПД_Товар_ДобавитьНомСредИдентТов(Строка);
>         НомСредИдентТов_ЗаполнитьИдентТрансУпак(НовыйЭлемент, ????);
>     КонецЦикла;
> КонецПроцедуры
> 
> Функция УПД_Товар_ДобавитьНомСредИдентТов(Item)
>     ItemIdentificationNumber = ОсновнойМодуль.НовыйЭлементСпискаXDTO(Item.ItemIdentificationNumbers);
>     Возврат ItemIdentificationNumber;
> КонецФункции
> 
> Процедура НомСредИдентТов_ЗаполнитьИдентТрансУпак(ItemIdentificationNumber, ИдентТрансУпак)
>     Если ItemIdentificationNumber = Неопределено Тогда
>         Возврат;
>     КонецЕсли;
>     ItemIdentificationNumber.TransPackageId = ИдентТрансУпак;
> КонецПроцедуры
> ```

Этот код еще актуален. Он решит мою проблему?

Подскажите как отлаживать подключаемый модуль?

**Comment by ButurlakinSemyon** [comment]
В функции ПодготовитьЭлектронныйДокумент добавляете новую процедуру. Название можете придумать сами, в качестве примера я привел "УПД_ИзменитьКонтент"(Content, Документ1С). Именно такой пример приведен в [генераторе ПМ](https://developer.kontur.ru/Docs/Diadoc_UM/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D0%B2/Generator_PM.html).
Далее описываете, что происходит в новой процедуре.

Для отладки ПМ в модуле необходимо:
1. Запустить 1С в режиме отладки.
2. Подключить файл ПМ в настройках модуля. Важно, чтобы ПМ был в файле, а не в справочнике.
3. Перезапустить модуль.
4. В конфигураторе установить точку остановы в нужном месте.

**Comment by Aleksandrovden** [comment]
> @Scherbakov-YA добрый день! Для заполнения маркировки необходимо доработать функцию "ПодготовитьЭлектронныйДокумент", например:
> 
> ```
> Функция ПодготовитьЭлектронныйДокумент(Параметры)
> 	// Имя шаблона: Произвольное изменение контента УПД
> 	Если ТипЗнч(Параметры) = Тип("Структура") И Параметры.Свойство("Результат_ИМ") Тогда
> 		Content		= Параметры.Результат.Content;
> 		Документ1С 	= Параметры.Результат.Документ1С;
> 		ВидДокументаРазвернутый = Параметры.ВидДокументаРазвернутый;
> 		ТипКонтента_XDTO = ВидДокументаРазвернутый.ТипКонтента;
> 		Если ВРЕГ(ТипКонтента_XDTO) = ВРЕГ("Utd820SellerContent") Тогда
> 			УПД_ИзменитьКонтент(Content, Документ1С);
> 		КонецЕсли;
> 		Возврат Истина;
> 	КонецЕсли;
> КонецФункции
> ```
> 
> В процедуре УПД_ИзменитьКонтент(Content, Документ1С) необходимо:
> 
> ```
> Процедура УПД_ИзменитьКонтент(Content, Документ1С)
>     Для Каждого Строка из Content.Table.Items Цикл
>         НовыйЭлемент = УПД_Товар_ДобавитьНомСредИдентТов(Строка);
>         НомСредИдентТов_ЗаполнитьИдентТрансУпак(НовыйЭлемент, ????);
>     КонецЦикла;
> КонецПроцедуры
> 
> Функция УПД_Товар_ДобавитьНомСредИдентТов(Item)
>     ItemIdentificationNumber = ОсновнойМодуль.НовыйЭлементСпискаXDTO(Item.ItemIdentificationNumbers);
>     Возврат ItemIdentificationNumber;
> КонецФункции
> 
> Процедура НомСредИдентТов_ЗаполнитьИдентТрансУпак(ItemIdentificationNumber, ИдентТрансУпак)
>     Если ItemIdentificationNumber = Неопределено Тогда
>         Возврат;
>     КонецЕсли;
>     ItemIdentificationNumber.TransPackageId = ИдентТрансУпак;
> КонецПроцедуры
> ```

Добрый день.
Как быть в ситуации когда у меня в ItemIdentificationNumbers пусто?
Т.е. код выше не работает, как заполнить данный массив?
Версия модуля 4.17.4.1922

![image](https://user-images.githubusercontent.com/110823343/183403489-13ee80e0-eeb6-4a7f-a2bd-6a8c14032858.png)

**Comment by Scherbakov-YA** [comment]
Все получилось, спасибо.

Возник еще вопрос. Коды для ОСУ теперь заполняются. А где теперь заполнить признак способа выбытия?
Т.е. если отгрузка идет например на социалку, т.е. последующей перепродажи не будет?

**Comment by ButurlakinSemyon** [comment]
Способ выбытия указывается в "ИнфПолФХЖ1". У честного знака есть [документация ](https://xn--80ajghhoc2aj1c8b.xn--p1ai/upload/docs/%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8_%D0%BF%D0%BE_%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%BB%D0%B5%D0%BD%D0%B8%D1%8E_%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%BE%D0%B2_%D0%AD%D0%94%D0%9E.html#_%D1%81%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F_%D0%BE_%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D0%B0%D1%85_%D0%B2%D1%8B%D0%B1%D1%8B%D1%82%D0%B8%D1%8F:~:text=%D1%85%D0%BE%D0%B7%D1%8F%D0%B9%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9%20%D0%B6%D0%B8%D0%B7%D0%BD%D0%B8%204-,4.2.%20%D0%A1%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F%20%D0%BE%20%D0%BF%D1%80%D0%B8%D1%87%D0%B8%D0%BD%D0%B0%D1%85%20%D0%B2%D1%8B%D0%B1%D1%8B%D1%82%D0%B8%D1%8F,-%D0%94%D0%BB%D1%8F%20%D0%BF%D0%B5%D1%80%D0%B5%D0%B4%D0%B0%D1%87%D0%B8%20%D1%81%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B9) с описанием.

В универсальном модуле можно вручную заполнить ИнфПолФХЖ1 на форме пакета:
![image](https://user-images.githubusercontent.com/74642650/184303379-3dd65a5a-9e1c-414f-a738-2accd2fff5d7.png)
В таком случае в XML это информация будет выглядеть так:
![image](https://user-images.githubusercontent.com/74642650/184303549-849a7d70-8ee0-40c0-846f-0132a4653a21.png)

Если такой вариант не подходит, то ИнфПолФХЖ1 можно заполнить в ПМ. Ниже приведу пример из [генератора ПМ](https://developer.kontur.ru/Docs/Diadoc_UM/%D0%9E%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%BE%D0%B2/Generator_PM.html):
`// Обработчики событий подключаемого модуля

Функция ПодготовитьЭлектронныйДокумент(Параметры)

	// Имя шаблона: 1_Добавление ИнфПолФХЖ1, значения реквизитов
	Если ТипЗнч(Параметры) = Тип("Структура") И Параметры.Свойство("Результат_ИМ") Тогда
				
		Content		= Параметры.Результат.Content;
		Документ1С 	= Параметры.Результат.Документ1С;

		ВидДокументаРазвернутый = Параметры.ВидДокументаРазвернутый;
		
		ТипКонтента_XDTO = ВидДокументаРазвернутый.ТипКонтента;
		
		Если ВРЕГ(ТипКонтента_XDTO) = ВРЕГ("Utd820SellerContent") Тогда
			
			УПД_ДобавитьИнфПолФХЖ1_ЗначенияРеквизитов(Content, Документ1С);

		КонецЕсли;

		Возврат Истина;

	КонецЕсли;

КонецФункции


// Вспомогательные методы с бизнес-логикой

Процедура УПД_ДобавитьИнфПолФХЖ1_ЗначенияРеквизитов(Content, Документ1С)
	
	// ключ - псевдоним поля: по этому ключу будет лежать полученное значение в структуре "ЗначенияРеквизитов"
	// значение - путь к данным: пишется путь до нужного реквизита, исключая начальный источник данных
	// может быть добавлено неограниченное количество полей, каждый элемент структуры - отдельное поле
	ТребуемыеРеквизиты = Новый Структура;
	ТребуемыеРеквизиты.Вставить("КомментарийКДоговору", "ДоговорКонтрагента.Комментарий"); // комментарий из договора документа 1С
	//ТребуемыеРеквизиты.Вставить("ИННКонтрагента", "Контрагент.ИНН"); // ИНН контрагента из документа 1С
	//ТребуемыеРеквизиты.Вставить("КППКонтрагента", "Контрагент.КПП"); // КПП контрагента из документа 1С
	//ТребуемыеРеквизиты.Вставить("Дата", "Дата"); // дата документа 1С
	
	// первый параметр - источник, из которого нужно получить данные
	// второй параметр - данные из этого источника, которые нужно получить
	ЗначенияРеквизитов = ОбщегоНазначения.ЗначенияРеквизитовОбъекта(Документ1С, ТребуемыеРеквизиты);
	
	Если ЗначениеЗаполнено(ЗначенияРеквизитов.КомментарийКДоговору) Тогда
		
		КомментарийКДоговору = СокрЛП(ЗначенияРеквизитов.КомментарийКДоговору);
		
		УПД_ДобавитьИнфПолФХЖ1(Content, "Комментарий к договору", КомментарийКДоговору);
		
	КонецЕсли;
	
	// обращения к полученным значениям реквизитов:
	// ИНН контрагента из документа 1С = ЗначенияРеквизитов.ИННКонтрагента
	// КПП контрагента из документа 1С = ЗначенияРеквизитов.КППКонтрагента
	// дата документа 1С = ЗначенияРеквизитов.Дата
	
КонецПроцедуры



// Общие функции для использования в обработчиках событий



// Методы работы с XDTO

Процедура УПД_ДобавитьИнфПолФХЖ1(Content, Key, Value)
	
	Если НЕ ЗначениеЗаполнено(Value) Тогда
		Возврат;
	КонецЕсли;
	
	AdditionalInfoId = Content.AdditionalInfoId;
	
	ОсновнойМодуль.ДобавитьИнформационноеПоле(AdditionalInfoId, Key, Value);

КонецПроцедуры
`

**Comment by Scherbakov-YA** [comment]
Подскажите, как работать с весовым товаром в части кодов ОСУ? Если в поле количество стоит вес, как определить количество марок для ОСУ? Делить на приблизительный вес штучки?

**Comment by Scherbakov-YA** [comment]
?
Как работать с весовым товаром?

**Comment by ButurlakinSemyon** [comment]
@Scherbakov-YA добрый день!
К сожалению, мы не можем вас проконсультировать по данному вопросу. Так как вопрос связан с рекомендациями работы с маркировкой. Мы можем подсказать лишь о том, какой инструмент использовать для заполнения, если такой существует в модуле. Про правила работы с маркировкой правильнее смотреть на сайте честного знака.
